---
# tasks file for expat
# delete expat_source_dir expat_app_dir

- name: "delete {{ expat_source_dir }} {{ expat_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ expat_source_dir }}"
      - "{{ expat_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ expat_install_user }}"
      group: "{{ expat_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ expat_dir }} {{ expat_app_base_dir }} {{ expat_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ expat_install_user }}"
      group: "{{ expat_install_group }}"
      mode: 0755
  with_items:
      - "{{ expat_dir }}"
      - "{{ expat_app_base_dir }}"
      - "{{ expat_app_dir }}"
  when:
      - expat_deploy_method == "binary" or expat_deploy_method == "source"

# source dir
- name: "mkdir {{ expat_dir }} {{ expat_source_base_dir }}  {{ expat_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ expat_install_user }}"
      group: "{{ expat_install_group }}"
      mode: 0755
  with_items:
      - "{{ expat_source_base_dir }}"
      - "{{ expat_source_dir }}"
  when:
      - expat_deploy_method == "source"

# service dir
- name: "mkdir {{ expat_data_dir }} {{ expat_conf_dir }} {{ expat_log_dir }} {{ expat_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ expat_install_user }}"
      group: "{{ expat_install_group }}"
      mode: 0755
  with_items:
      - "{{ expat_data_dir }}"
      - "{{ expat_conf_dir }}"
      - "{{ expat_log_dir }}"
      - "{{ expat_tmp_dir }}"
  when:
      - expat_port is defined
