---
change_hosts: false
dns_servers:
    - 114.114.114.114
    - 8.8.8.8
alertmanager_port: 9093

# for 10.4.0 compile
gmp_version: "6.1.0"
mpfr_version: "3.1.6"
mpc_version: "1.0.3"
isl_version: "0.18"

#

