---
# defaults file for kazoo
# python-kazoo-2.0-2.el7.noarch.rpm >> kazoo-2.0.rpm

kazoo_install_user: "{{ansible_user}}"
kazoo_install_group: "{{ansible_user}}"
kazoo_version: "2.0"
# standalone/cluster/pseudo_cluster
kazoo_deploy_mode: "standalone"
# binary/source/rpm/yum/dnf
kazoo_deploy_method: "rpm"
kazoo_base_url: "{{base_url}}"
kazoo_base_url_remote: "http://172.17.135.146:1510/gtms/repo/x64/centos/7"

kazoo_package_suffix: ".tar.gz"
kazoo_package_name_rpm: "kazoo-{{kazoo_version}}.rpm"
kazoo_package_name_binary: "kazoo-{{kazoo_version}}-{{ansible_architecture}}{{kazoo_package_suffix}}"
kazoo_package_name_source: "kazoo-{{kazoo_version}}{{kazoo_package_suffix}}"

kazoo_dir: "{{base_dir}}/kazoo"
kazoo_app_dir: "{{base_dir}}/kazoo/app"
kazoo_base_dir: "{{kazoo_app_dir}}/kazoo-{{kazoo_version}}"
kazoo_source_dir: "{{kazoo_app_dir}}/source/kazoo-{{kazoo_version}}"
