---
# tasks file for tar
# delete tar_source_dir tar_app_dir

- name: "delete {{ tar_source_dir }} {{ tar_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ tar_source_dir }}"
      - "{{ tar_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tar_install_user }}"
      group: "{{ tar_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ tar_dir }} {{ tar_app_base_dir }} {{ tar_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tar_install_user }}"
      group: "{{ tar_install_group }}"
      mode: 0755
  with_items:
      - "{{ tar_dir }}"
      - "{{ tar_app_base_dir }}"
      - "{{ tar_app_dir }}"
  when:
      - tar_deploy_method == "binary" or tar_deploy_method == "source"

# source dir
- name: "mkdir {{ tar_dir }} {{ tar_source_base_dir }}  {{ tar_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tar_install_user }}"
      group: "{{ tar_install_group }}"
      mode: 0755
  with_items:
      - "{{ tar_source_base_dir }}"
      - "{{ tar_source_dir }}"
      - "{{ tar_build_dir }}"
  when:
      - tar_deploy_method == "source"

# service dir
- name: "mkdir {{ tar_data_dir }} {{ tar_conf_dir }} {{ tar_log_dir }} {{ tar_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tar_install_user }}"
      group: "{{ tar_install_group }}"
      mode: 0755
  with_items:
      - "{{ tar_data_dir }}"
      - "{{ tar_conf_dir }}"
      - "{{ tar_log_dir }}"
      - "{{ tar_tmp_dir }}"
  when:
      - tar_port is defined
