---
# defaults file for libunistring
# https://ftp.gnu.org/gnu/libunistring/libunistring-1.3.tar.gz
libunistring_install_user: "{{ ansible_user }}"
libunistring_install_group: "{{ ansible_user }}"
libunistring_version: "1.3"
libunistring_base_url: "{{ base_url }}"
libunistring_base_url_remote: "https://ftp.gnu.org/gnu/libunistring"

# binary/source

libunistring_deploy_mode: "source"
libunistring_package_suffix: ".tar.gz"
libunistring_package_name_binary: "libunistring-{{ libunistring_version }}"
libunistring_package_name_source: "libunistring-{{ libunistring_version }}"

libunistring_dir: "{{ base_dir }}/libunistring"
libunistring_app_dir: "{{ base_dir }}/libunistring/app"
libunistring_base_dir: "{{ libunistring_app_dir }}/libunistring-{{ libunistring_version }}"
libunistring_source_dir: "{{ libunistring_app_dir }}/source/libunistring-{{ libunistring_version }}"
