---
# defaults file for mysql
# mysql_deploy_mode: bin,source,rpm
# mysql_url: local,url

# mysql-8.0.32-aarch64.tar.gz
# mysql-8.0.32-x86_64.tar.gz
# mysql-8.0.32.tar.gz

mysql_port: "8032"
mysql_version: "8.0.32"
mysql_base_url: "ftp://ip:port/"
mysql_deploy_mode: "bin"
mysql_url: "local"
mgr: true
mysql_bin_package_name: "mysql-{{ mysql_version }}"
mysql_source_package_name: "mysql-{{ mysql_version }}"

mysql_dir: "{{ base_dir }}/mysql"
mysql_app_dir: "{{ base_dir }}/mysql/app"
mysql_base_dir: "{{ base_dir }}/mysql/app/mysql-{{ mysql_version }}"
mysql_conf_dir: "{{ base_dir }}/mysql/conf"
mysql_data_dir: "{{ base_dir }}/mysql/data"
mysql_log_dir: "{{ base_dir }}/mysql/log"
mysql_tmp_dir: "{{ base_dir }}/mysql/tmp"
mysql_source_dir: "{{ base_dir }}/mysql-{{ mysql_version }}"

