---
# defaults file for mysql
# mysql_deploy_mode: bin,source,rpm
# mysql_url: local,url
# https://archive.apache.org/dist/httpd/httpd-2.4.60.tar.gz
mysql_port: "8032"
mysql_version: "8.0.32"
mysql_deploy_mode: "bin"
mysql_url: "local"
mysql_package_name: "httpd-2.4.60.tar.gz"

mysql_dir: "{{ base_dir }}/mysql"
mysql_app_dir: "{{ base_dir }}/mysql/app"
mysql_base_dir: "{{ base_dir }}/mysql/app/mysql-{{ mysql_version }}"
mysql_conf_dir: "{{ base_dir }}/mysql/conf"
mysql_data_dir: "{{ base_dir }}/mysql/data"
mysql_log_dir: "{{ base_dir }}/mysql/log"
mysql_tmp_dir: "{{ base_dir }}/mysql/tmp"
mysql_prom_dir: "{{ base_dir }}/mysql/prom"













