---
# tasks file for bison
- name: "remove {{ bison_source_dir }} {{ bison_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ bison_source_dir }}"
          - "{{ bison_base_dir }}"

- name: "mkdir for bison"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ bison_install_user }}"
          group: "{{ bison_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ bison_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ bison_app_dir }}"
          - "{{ bison_base_dir }}"

- name: "mkdir {{ bison_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ bison_install_user }}"
          group: "{{ bison_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ bison_source_dir }}"
  when: bison_deploy_mode == "source"
