---
# tasks file for libtirpc
# delete libtirpc_source_dir libtirpc_app_dir

- name: "delete {{ libtirpc_source_dir }} {{ libtirpc_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ libtirpc_source_dir }}"
      - "{{ libtirpc_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtirpc_install_user }}"
      group: "{{ libtirpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ libtirpc_dir }} {{ libtirpc_app_base_dir }} {{ libtirpc_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtirpc_install_user }}"
      group: "{{ libtirpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ libtirpc_dir }}"
      - "{{ libtirpc_app_base_dir }}"
      - "{{ libtirpc_app_dir }}"
  when:
      - libtirpc_deploy_method == "binary" or libtirpc_deploy_method == "source"

# source dir
- name: "mkdir {{ libtirpc_dir }} {{ libtirpc_source_base_dir }}  {{ libtirpc_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtirpc_install_user }}"
      group: "{{ libtirpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ libtirpc_source_base_dir }}"
      - "{{ libtirpc_source_dir }}"
      - "{{ libtirpc_build_dir }}"
  when:
      - libtirpc_deploy_method == "source"

# service dir
- name: "mkdir {{ libtirpc_data_dir }} {{ libtirpc_conf_dir }} {{ libtirpc_log_dir }} {{ libtirpc_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtirpc_install_user }}"
      group: "{{ libtirpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ libtirpc_data_dir }}"
      - "{{ libtirpc_conf_dir }}"
      - "{{ libtirpc_log_dir }}"
      - "{{ libtirpc_tmp_dir }}"
  when:
      - libtirpc_port is defined
