---
# tasks file for libtirpc
- name: "remove {{ libtirpc_source_dir }} {{ libtirpc_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ libtirpc_source_dir }}"
          - "{{ libtirpc_base_dir }}"

- name: "mkdir for libtirpc"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ libtirpc_install_user }}"
          group: "{{ libtirpc_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ libtirpc_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ libtirpc_app_dir }}"
          - "{{ libtirpc_base_dir }}"

- name: "mkdir {{ libtirpc_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ libtirpc_install_user }}"
          group: "{{ libtirpc_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ libtirpc_source_dir }}"
  when: libtirpc_deploy_method == "source"
