---
# tasks file for ncurses

- name: "date '+%Y%m%dT%H%M%S'"
  become: true
  shell:
      cmd: "date '+%Y%m%dT%H%M%S'"
  register: date_output

# check ncurses_port
- name: "lsof -i:{{ ncurses_port }}"
  become: true
  shell:
      cmd: "lsof -i:{{ ncurses_port }}"
  register: ncurses_port_check_output
  ignore_errors: true
  when: ncurses_port is defined

- name: "check ncurses port"
  become: true
  fail:
      msg: "ncursesd端口被占用,可使用: ps aux|grep ncursesd"
  when:
      - ncurses_port is defined
      - ncurses_port_check_output is defined
      - ncurses_port_check_output.rc == 0
