---
# tasks file for ncurses
# delete ncurses_source_dir ncurses_app_dir

- name: "delete {{ ncurses_source_dir }} {{ ncurses_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ ncurses_source_dir }}"
      - "{{ ncurses_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ncurses_install_user }}"
      group: "{{ ncurses_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ ncurses_dir }} {{ ncurses_app_base_dir }} {{ ncurses_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ncurses_install_user }}"
      group: "{{ ncurses_install_group }}"
      mode: 0755
  with_items:
      - "{{ ncurses_dir }}"
      - "{{ ncurses_app_base_dir }}"
      - "{{ ncurses_app_dir }}"
  when:
      - ncurses_deploy_method == "binary" or ncurses_deploy_method == "source"

# source dir
- name: "mkdir {{ ncurses_dir }} {{ ncurses_source_base_dir }}  {{ ncurses_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ncurses_install_user }}"
      group: "{{ ncurses_install_group }}"
      mode: 0755
  with_items:
      - "{{ ncurses_source_base_dir }}"
      - "{{ ncurses_source_dir }}"
  when:
      - ncurses_deploy_method == "source"

# service dir
- name: "mkdir {{ ncurses_data_dir }} {{ ncurses_conf_dir }} {{ ncurses_log_dir }} {{ ncurses_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ncurses_install_user }}"
      group: "{{ ncurses_install_group }}"
      mode: 0755
  with_items:
      - "{{ ncurses_data_dir }}"
      - "{{ ncurses_conf_dir }}"
      - "{{ ncurses_log_dir }}"
      - "{{ ncurses_tmp_dir }}"
  when:
      - ncurses_port is defined
