---
# tasks file for ncurses
- name: "remove {{ ncurses_source_dir }} {{ ncurses_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ ncurses_source_dir }}"
          - "{{ ncurses_base_dir }}"

- name: "mkdir for ncurses"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ ncurses_install_user }}"
          group: "{{ ncurses_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ ncurses_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ ncurses_app_dir }}"
          - "{{ ncurses_base_dir }}"

- name: "mkdir {{ ncurses_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ ncurses_install_user }}"
          group: "{{ ncurses_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ ncurses_source_dir }}"
  when: ncurses_deploy_method == "source"
