---
# tasks file for zstd
- name: "remove {{ zstd_source_dir }} {{ zstd_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ zstd_source_dir }}"
          - "{{ zstd_base_dir }}"

- name: "mkdir for zstd"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ zstd_install_user }}"
          group: "{{ zstd_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ zstd_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ zstd_app_dir }}"
          - "{{ zstd_base_dir }}"

- name: "mkdir {{ zstd_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ zstd_install_user }}"
          group: "{{ zstd_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ zstd_source_dir }}"
  when: zstd_deploy_mode == "source"
