---
# tasks file for zstd
# https://github.com/facebook/zstd/archive/refs/tags/v1.5.6.tar.gz

- include_tasks: 01-dir.yml

- name: "02-install_binary.yml"
  include_tasks: 02-install_binary.yml
  when: zstd_deploy_method == "binary"

- name: "02-install_source.yml"
  include_tasks: 02-install_source.yml
  when: zstd_deploy_method == "source"

- include_tasks: 03-init.yml
