---
# defaults file for mpfr
# https://gcc.gnu.org/pub/gcc/infrastructure/mpfr-3.1.6.tar.bz2

# user
mpfr_install_user: "{{ ansible_user }}"
mpfr_install_group: "{{ ansible_user }}"
mpfr_version: "3.1.6"
# mpfr_port: "8032"

# standalone/cluster/pseudo_cluster
mpfr_deploy_mode: "standalone"

# binary/source/rpm/yum/dnf
mpfr_deploy_method: "source"

# url
mpfr_base_url: "{{ base_url }}"
mpfr_base_url_remote: "https://gcc.gnu.org/pub/gcc/infrastructure"

# package
mpfr_package_suffix: ".tar.bz2"
mpfr_package_name_rpm: "mpfr-{{ mpfr_version }}.rpm"
mpfr_package_name_binary: "mpfr-{{ mpfr_version }}-{{ ansible_architecture }}{{ mpfr_package_suffix }}"
mpfr_package_name_source: "mpfr-{{ mpfr_version }}{{ mpfr_package_suffix }}"
mpfr_package_name: "{% if mpfr_deploy_method == 'rpm' %}{{ mpfr_package_name_rpm }}{% elif mpfr_deploy_method == 'binary' %}{{ mpfr_package_name_binary }}{% elif mpfr_deploy_method == 'source' %}{{ mpfr_package_name_source }}{% else %}{{ mpfr_package_name_source }}{% endif %}"

# 一台机器上部署相同服务时，通过不同端口号和不同的base_dir来区分是最佳的，这样不用修改目录结构
# 1. 通过变更base_dir和端口
# /data
# /data/mpfr
# /data/mpfr/data
# /data/mpfr/conf
# /data/mpfr/log
# /data/mpfr/tmp
# /data/mpfr/source
# /data/mpfr/app
# /data/mpfr/app/mpfr-2.44
# /data/mpfr/app/mpfr-2.44/bin
# /data/mpfr/app/mpfr-2.44/lib
# /data/mpfr/app/mpfr-2.44/lib/pkgconfig
# /data/mpfr/app/mpfr-2.44/include
# /data/mpfr/app/mpfr-2.44/share
# /data/mpfr/source/mpfr-2.44
mpfr_dir: "{{ base_dir }}/mpfr"
mpfr_data_dir: "{{ mpfr_dir }}/data"
mpfr_conf_dir: "{{ mpfr_dir }}/conf"
mpfr_log_dir: "{{ mpfr_dir }}/log"
mpfr_tmp_dir: "{{ mpfr_dir }}/tmp"
mpfr_app_base_dir: "{{ mpfr_dir }}/app"
mpfr_source_base_dir: "{{ mpfr_dir }}/source"
mpfr_app_dir: "{{ mpfr_app_base_dir }}/mpfr-{{ mpfr_version }}"
mpfr_bin_dir: "{{ mpfr_app_dir }}/bin"
mpfr_lib_dir: "{{ mpfr_app_dir }}/lib"
mpfr_include_dir: "{{ mpfr_app_dir }}/include"
mpfr_share_dir: "{{ mpfr_app_dir }}/share"
mpfr_pkgconfig_dir: "{{ mpfr_lib_dir }}/pkgconfig"
mpfr_source_dir: "{{ mpfr_source_base_dir }}/mpfr-{{ mpfr_version }}"
