---
# tasks file for flex
- name: "remove {{flex_source_dir}} {{flex_base_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: absent
  with_items:
      - "{{flex_source_dir}}"
      - "{{flex_base_dir}}"

- name: "mkdir for flex"
  become: true
  file:
      path: "{{item}}"
      state: directory
      owner: "{{flex_install_user}}"
      group: "{{flex_install_group}}"
      mode: 0755
  with_items:
      - "{{base_dir}}"
      - "{{flex_dir}}"
      - "{{install_tmpdir}}"
      - "{{flex_app_dir}}"
      - "{{flex_base_dir}}"

- name: "mkdir {{flex_source_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: "{{flex_install_user}}"
      group: "{{flex_install_group}}"
  with_items:
      - "{{base_dir}}"
      - "{{flex_source_dir}}"
  when: flex_deploy_method == "source"
