---
# tasks file for sed
# delete sed_source_dir sed_app_dir

- name: "delete {{ sed_source_dir }} {{ sed_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ sed_source_dir }}"
      - "{{ sed_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ sed_install_user }}"
      group: "{{ sed_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ sed_dir }} {{ sed_app_base_dir }} {{ sed_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ sed_install_user }}"
      group: "{{ sed_install_group }}"
      mode: 0755
  with_items:
      - "{{ sed_dir }}"
      - "{{ sed_app_base_dir }}"
      - "{{ sed_app_dir }}"
  when:
      - sed_deploy_method == "binary" or sed_deploy_method == "source"

# source dir
- name: "mkdir {{ sed_dir }} {{ sed_source_base_dir }}  {{ sed_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ sed_install_user }}"
      group: "{{ sed_install_group }}"
      mode: 0755
  with_items:
      - "{{ sed_source_base_dir }}"
      - "{{ sed_source_dir }}"
  when:
      - sed_deploy_method == "source"

# service dir
- name: "mkdir {{ sed_data_dir }} {{ sed_conf_dir }} {{ sed_log_dir }} {{ sed_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ sed_install_user }}"
      group: "{{ sed_install_group }}"
      mode: 0755
  with_items:
      - "{{ sed_data_dir }}"
      - "{{ sed_conf_dir }}"
      - "{{ sed_log_dir }}"
      - "{{ sed_tmp_dir }}"
  when:
      - sed_port is defined
