---
# tasks file for gcc
- name: "remove {{ gcc_source_dir }} {{ gcc_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ gcc_source_dir }}"
          - "{{ gcc_base_dir }}"

- name: "mkdir for gcc"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ gcc_install_user }}"
          group: "{{ gcc_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ gcc_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ gcc_app_dir }}"
          - "{{ gcc_base_dir }}"

- name: "mkdir {{ gcc_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ gcc_install_user }}"
          group: "{{ gcc_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ gcc_source_dir }}"
  when: gcc_deploy_mode == "source"
