---
# tasks file for autogen
- name: "remove {{ autogen_source_dir }} {{ autogen_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ autogen_source_dir }}"
          - "{{ autogen_base_dir }}"

- name: "mkdir for autogen"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ autogen_install_user }}"
          group: "{{ autogen_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ autogen_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ autogen_app_dir }}"
          - "{{ autogen_base_dir }}"

- name: "mkdir {{ autogen_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ autogen_install_user }}"
          group: "{{ autogen_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ autogen_source_dir }}"
  when: autogen_deploy_method == "source"
