---
# tasks file for tcl
# delete tcl_source_dir tcl_app_dir

- name: "delete {{ tcl_source_dir }} {{ tcl_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ tcl_source_dir }}"
      - "{{ tcl_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tcl_install_user }}"
      group: "{{ tcl_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ tcl_dir }} {{ tcl_app_base_dir }} {{ tcl_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tcl_install_user }}"
      group: "{{ tcl_install_group }}"
      mode: 0755
  with_items:
      - "{{ tcl_dir }}"
      - "{{ tcl_app_base_dir }}"
      - "{{ tcl_app_dir }}"
  when:
      - tcl_deploy_method == "binary" or tcl_deploy_method == "source"

# source dir
- name: "mkdir {{ tcl_dir }} {{ tcl_source_base_dir }}  {{ tcl_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tcl_install_user }}"
      group: "{{ tcl_install_group }}"
      mode: 0755
  with_items:
      - "{{ tcl_source_base_dir }}"
      - "{{ tcl_source_dir }}"
      - "{{ tcl_build_dir }}"
  when:
      - tcl_deploy_method == "source"

# service dir
- name: "mkdir {{ tcl_data_dir }} {{ tcl_conf_dir }} {{ tcl_log_dir }} {{ tcl_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ tcl_install_user }}"
      group: "{{ tcl_install_group }}"
      mode: 0755
  with_items:
      - "{{ tcl_data_dir }}"
      - "{{ tcl_conf_dir }}"
      - "{{ tcl_log_dir }}"
      - "{{ tcl_tmp_dir }}"
  when:
      - tcl_port is defined
