---
# tasks file for glibc
# delete glibc_source_dir glibc_app_dir

- name: "delete {{ glibc_source_dir }} {{ glibc_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ glibc_source_dir }}"
      - "{{ glibc_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ glibc_install_user }}"
      group: "{{ glibc_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ glibc_dir }} {{ glibc_app_base_dir }} {{ glibc_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ glibc_install_user }}"
      group: "{{ glibc_install_group }}"
      mode: 0755
  with_items:
      - "{{ glibc_dir }}"
      - "{{ glibc_app_base_dir }}"
      - "{{ glibc_app_dir }}"
  when:
      - glibc_deploy_method == "binary" or glibc_deploy_method == "source"

# source dir
- name: "mkdir {{ glibc_dir }} {{ glibc_source_base_dir }}  {{ glibc_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ glibc_install_user }}"
      group: "{{ glibc_install_group }}"
      mode: 0755
  with_items:
      - "{{ glibc_source_base_dir }}"
      - "{{ glibc_source_dir }}"
      - "{{ glibc_build_dir }}"
  when:
      - glibc_deploy_method == "source"

# service dir
- name: "mkdir {{ glibc_data_dir }} {{ glibc_conf_dir }} {{ glibc_log_dir }} {{ glibc_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ glibc_install_user }}"
      group: "{{ glibc_install_group }}"
      mode: 0755
  with_items:
      - "{{ glibc_data_dir }}"
      - "{{ glibc_conf_dir }}"
      - "{{ glibc_log_dir }}"
      - "{{ glibc_tmp_dir }}"
  when:
      - glibc_port is defined
