---
# tasks file for kazoo by rpm

# 检查远程主机上的文件是否存在
# 检查远程主机上的文件是否完整
- name: "Check file exists first: {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  stat:
      path: "{{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  register: check_file_exists_first

- name: "Check file valid first: {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  command: "gzip -t {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  register: check_file_valid_first
  ignore_errors: true
  when: check_file_exists_first.stat.exists

############################################
# 从控制机拷贝
############################################
- name: "Check file exists on ansible host: {{role_path}}/files/{{kazoo_package_name_rpm}}"
  delegate_to: localhost
  run_once: true
  stat:
      path: "{{role_path}}/files/{{kazoo_package_name_rpm}}"
  register: local_file_stat

- name: "Copy file from control machine if remote file is missing or invalid"
  become: true
  copy:
      src: "{{kazoo_package_name_rpm}}"
      dest: "{{install_tmpdir}}/"
      owner: "{{kazoo_install_user}}"
      group: "{{kazoo_install_group}}"
      mode: 0755
  when:
      - (not check_file_exists_first.stat.exists or check_file_valid_first.rc != 0)
      - local_file_stat.stat.exists

#################################################
# 从 kazoo_base_url 下载
#################################################

- name: "Check file exists second: {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  stat:
      path: "{{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  register: check_file_exists_second

- name: "Check file valid second: {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  command: "gzip -t {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  register: check_file_valid_second
  ignore_errors: true
  when: check_file_exists_second.stat.exists

- name: "Download file from kazoo_base_url: from {{kazoo_base_url}}/{{kazoo_package_name_rpm}} to {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  get_url:
      url: "{{kazoo_base_url}}/{{kazoo_package_name_rpm}}"
      dest: "{{install_tmpdir}}/"
      owner: "{{kazoo_install_user}}"
      group: "{{kazoo_install_group}}"
      mode: 0755
      timeout: 600
  when:
      - (not check_file_exists_second.stat.exists or check_file_valid_second.rc != 0)
  ignore_errors: true

#################################################
# 尝试从 kazoo_base_url_remote 下载
#################################################

- name: "Check file exists third: {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  stat:
      path: "{{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  register: check_file_exists_third

- name: "Check file valid third: {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  command: "gzip -t {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  register: check_file_valid_third
  ignore_errors: true
  when: check_file_exists_third.stat.exists

- name: "Download file from kazoo_base_url_remote: from {{kazoo_base_url_remote}}/{{kazoo_package_name_rpm}} to {{install_tmpdir}}/{{kazoo_package_name_rpm}}"
  get_url:
      url: "{{kazoo_base_url_remote}}/python-kazoo-2.0-2.el7.noarch.rpm"
      dest: "{{install_tmpdir}}/{{kazoo_package_name_rpm}}"
      owner: "{{kazoo_install_user}}"
      group: "{{kazoo_install_group}}"
      mode: 0755
      timeout: 600
  when:
      - (not check_file_exists_third.stat.exists or check_file_valid_third.rc != 0)

#################################################
# install
#################################################
- name: "rpm -ivh {{kazoo_package_name_rpm}}"
  become: true
  shell:
      chdir: "{{install_tmpdir}}/"
      cmd: "rpm -ivh {{kazoo_package_name_rpm}}"

- name: "rpm -qa | grep kazoo"
  become: true
  shell:
      chdir: "{{install_tmpdir}}/"
      cmd: "rpm -qa | grep kazoo"
