---
# tasks file for jemalloc
- name: "remove {{jemalloc_source_dir}} {{jemalloc_base_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: absent
  with_items:
      - "{{jemalloc_source_dir}}"
      - "{{jemalloc_base_dir}}"

- name: "mkdir for jemalloc"
  become: true
  file:
      path: "{{item}}"
      state: directory
      owner: "{{jemalloc_install_user}}"
      group: "{{jemalloc_install_group}}"
      mode: 0755
  with_items:
      - "{{base_dir}}"
      - "{{jemalloc_dir}}"
      - "{{install_tmpdir}}"
      - "{{jemalloc_app_dir}}"
      - "{{jemalloc_base_dir}}"

- name: "mkdir {{jemalloc_source_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: "{{jemalloc_install_user}}"
      group: "{{jemalloc_install_group}}"
  with_items:
      - "{{base_dir}}"
      - "{{jemalloc_source_dir}}"
  when: jemalloc_deploy_method == "source"
