---
# tasks file for diffutils
- name: "remove {{ diffutils_source_dir }} {{ diffutils_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ diffutils_source_dir }}"
          - "{{ diffutils_base_dir }}"

- name: "mkdir for diffutils"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ diffutils_install_user }}"
          group: "{{ diffutils_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ diffutils_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ diffutils_app_dir }}"
          - "{{ diffutils_base_dir }}"

- name: "mkdir {{ diffutils_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ diffutils_install_user }}"
          group: "{{ diffutils_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ diffutils_source_dir }}"
  when: diffutils_deploy_mode == "source"
