---
# tasks file for diffutils
# delete diffutils_source_dir diffutils_app_dir

- name: "delete {{ diffutils_source_dir }} {{ diffutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ diffutils_source_dir }}"
      - "{{ diffutils_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ diffutils_install_user }}"
      group: "{{ diffutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ diffutils_dir }} {{ diffutils_app_base_dir }} {{ diffutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ diffutils_install_user }}"
      group: "{{ diffutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ diffutils_dir }}"
      - "{{ diffutils_app_base_dir }}"
      - "{{ diffutils_app_dir }}"
  when:
      - diffutils_deploy_method == "binary" or diffutils_deploy_method == "source"

# source dir
- name: "mkdir {{ diffutils_dir }} {{ diffutils_source_base_dir }}  {{ diffutils_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ diffutils_install_user }}"
      group: "{{ diffutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ diffutils_source_base_dir }}"
      - "{{ diffutils_source_dir }}"
  when:
      - diffutils_deploy_method == "source"

# service dir
- name: "mkdir {{ diffutils_data_dir }} {{ diffutils_conf_dir }} {{ diffutils_log_dir }} {{ diffutils_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ diffutils_install_user }}"
      group: "{{ diffutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ diffutils_data_dir }}"
      - "{{ diffutils_conf_dir }}"
      - "{{ diffutils_log_dir }}"
      - "{{ diffutils_tmp_dir }}"
  when:
      - diffutils_port is defined
