---
# tasks file for libev
- name: "remove {{ libev_source_dir }} {{ libev_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ libev_source_dir }}"
          - "{{ libev_base_dir }}"

- name: "mkdir for libev"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ libev_install_user }}"
          group: "{{ libev_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ libev_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ libev_app_dir }}"
          - "{{ libev_base_dir }}"

- name: "mkdir {{ libev_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ libev_install_user }}"
          group: "{{ libev_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ libev_source_dir }}"
  when: libev_deploy_mode == "source"
