---
# tasks file for inetutils
# delete inetutils_source_dir inetutils_app_dir

- name: "delete {{ inetutils_source_dir }} {{ inetutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ inetutils_source_dir }}"
      - "{{ inetutils_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ inetutils_install_user }}"
      group: "{{ inetutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ inetutils_dir }} {{ inetutils_app_base_dir }} {{ inetutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ inetutils_install_user }}"
      group: "{{ inetutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ inetutils_dir }}"
      - "{{ inetutils_app_base_dir }}"
      - "{{ inetutils_app_dir }}"
  when:
      - inetutils_deploy_method == "binary" or inetutils_deploy_method == "source"

# source dir
- name: "mkdir {{ inetutils_dir }} {{ inetutils_source_base_dir }}  {{ inetutils_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ inetutils_install_user }}"
      group: "{{ inetutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ inetutils_source_base_dir }}"
      - "{{ inetutils_source_dir }}"
  when:
      - inetutils_deploy_method == "source"

# service dir
- name: "mkdir {{ inetutils_data_dir }} {{ inetutils_conf_dir }} {{ inetutils_log_dir }} {{ inetutils_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ inetutils_install_user }}"
      group: "{{ inetutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ inetutils_data_dir }}"
      - "{{ inetutils_conf_dir }}"
      - "{{ inetutils_log_dir }}"
      - "{{ inetutils_tmp_dir }}"
  when:
      - inetutils_port is defined
