---
# tasks file for gettext

- name: "date '+%Y%m%dT%H%M%S'"
  become: true
  shell:
      cmd: "date '+%Y%m%dT%H%M%S'"
  register: date_output

# check gettext_port
- name: "lsof -i:{{ gettext_port }}"
  become: true
  shell:
      cmd: "lsof -i:{{ gettext_port }}"
  register: gettext_port_check_output
  ignore_errors: true
  when: gettext_port is defined

- name: "check gettext port"
  become: true
  fail:
      msg: "gettextd端口被占用,可使用: ps aux|grep gettextd"
  when:
      - gettext_port is defined
      - gettext_port_check_output is defined
      - gettext_port_check_output.rc == 0
