---
# tasks file for gettext
# delete gettext_source_dir gettext_app_dir

- name: "delete {{ gettext_source_dir }} {{ gettext_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ gettext_source_dir }}"
      - "{{ gettext_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gettext_install_user }}"
      group: "{{ gettext_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ gettext_dir }} {{ gettext_app_base_dir }} {{ gettext_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gettext_install_user }}"
      group: "{{ gettext_install_group }}"
      mode: 0755
  with_items:
      - "{{ gettext_dir }}"
      - "{{ gettext_app_base_dir }}"
      - "{{ gettext_app_dir }}"
  when:
      - gettext_deploy_method == "binary" or gettext_deploy_method == "source"

# source dir
- name: "mkdir {{ gettext_dir }} {{ gettext_source_base_dir }}  {{ gettext_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gettext_install_user }}"
      group: "{{ gettext_install_group }}"
      mode: 0755
  with_items:
      - "{{ gettext_source_base_dir }}"
      - "{{ gettext_source_dir }}"
  when:
      - gettext_deploy_method == "source"

# service dir
- name: "mkdir {{ gettext_data_dir }} {{ gettext_conf_dir }} {{ gettext_log_dir }} {{ gettext_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gettext_install_user }}"
      group: "{{ gettext_install_group }}"
      mode: 0755
  with_items:
      - "{{ gettext_data_dir }}"
      - "{{ gettext_conf_dir }}"
      - "{{ gettext_log_dir }}"
      - "{{ gettext_tmp_dir }}"
  when:
      - gettext_port is defined
