---
# tasks file for gettext
- name: "remove {{ gettext_source_dir }} {{ gettext_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ gettext_source_dir }}"
          - "{{ gettext_base_dir }}"

- name: "mkdir for gettext"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ gettext_install_user }}"
          group: "{{ gettext_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ gettext_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ gettext_app_dir }}"
          - "{{ gettext_base_dir }}"

- name: "mkdir {{ gettext_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ gettext_install_user }}"
          group: "{{ gettext_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ gettext_source_dir }}"
  when: gettext_deploy_mode == "source"
