---
# tasks file for patch
- name: "remove {{ patch_source_dir }} {{ patch_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ patch_source_dir }}"
          - "{{ patch_base_dir }}"

- name: "mkdir for patch"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ patch_install_user }}"
          group: "{{ patch_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ patch_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ patch_app_dir }}"
          - "{{ patch_base_dir }}"

- name: "mkdir {{ patch_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ patch_install_user }}"
          group: "{{ patch_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ patch_source_dir }}"
  when: patch_deploy_mode == "source"
