---
# tasks file for patch
# delete patch_source_dir patch_app_dir

- name: "delete {{ patch_source_dir }} {{ patch_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ patch_source_dir }}"
      - "{{ patch_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ patch_install_user }}"
      group: "{{ patch_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ patch_dir }} {{ patch_app_base_dir }} {{ patch_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ patch_install_user }}"
      group: "{{ patch_install_group }}"
      mode: 0755
  with_items:
      - "{{ patch_dir }}"
      - "{{ patch_app_base_dir }}"
      - "{{ patch_app_dir }}"
  when:
      - patch_deploy_method == "binary" or patch_deploy_method == "source"

# source dir
- name: "mkdir {{ patch_dir }} {{ patch_source_base_dir }}  {{ patch_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ patch_install_user }}"
      group: "{{ patch_install_group }}"
      mode: 0755
  with_items:
      - "{{ patch_source_base_dir }}"
      - "{{ patch_source_dir }}"
  when:
      - patch_deploy_method == "source"

# service dir
- name: "mkdir {{ patch_data_dir }} {{ patch_conf_dir }} {{ patch_log_dir }} {{ patch_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ patch_install_user }}"
      group: "{{ patch_install_group }}"
      mode: 0755
  with_items:
      - "{{ patch_data_dir }}"
      - "{{ patch_conf_dir }}"
      - "{{ patch_log_dir }}"
      - "{{ patch_tmp_dir }}"
  when:
      - patch_port is defined
