---
# tasks file for texinfo
# delete texinfo_source_dir texinfo_app_dir

- name: "delete {{ texinfo_source_dir }} {{ texinfo_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ texinfo_source_dir }}"
      - "{{ texinfo_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ texinfo_install_user }}"
      group: "{{ texinfo_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ texinfo_dir }} {{ texinfo_app_base_dir }} {{ texinfo_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ texinfo_install_user }}"
      group: "{{ texinfo_install_group }}"
      mode: 0755
  with_items:
      - "{{ texinfo_dir }}"
      - "{{ texinfo_app_base_dir }}"
      - "{{ texinfo_app_dir }}"
  when:
      - texinfo_deploy_method == "binary" or texinfo_deploy_method == "source"

# source dir
- name: "mkdir {{ texinfo_dir }} {{ texinfo_source_base_dir }}  {{ texinfo_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ texinfo_install_user }}"
      group: "{{ texinfo_install_group }}"
      mode: 0755
  with_items:
      - "{{ texinfo_source_base_dir }}"
      - "{{ texinfo_source_dir }}"
  when:
      - texinfo_deploy_method == "source"

# service dir
- name: "mkdir {{ texinfo_data_dir }} {{ texinfo_conf_dir }} {{ texinfo_log_dir }} {{ texinfo_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ texinfo_install_user }}"
      group: "{{ texinfo_install_group }}"
      mode: 0755
  with_items:
      - "{{ texinfo_data_dir }}"
      - "{{ texinfo_conf_dir }}"
      - "{{ texinfo_log_dir }}"
      - "{{ texinfo_tmp_dir }}"
  when:
      - texinfo_port is defined
