---
# tasks file for texinfo
- name: "remove {{ texinfo_source_dir }} {{ texinfo_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ texinfo_source_dir }}"
          - "{{ texinfo_base_dir }}"

- name: "mkdir for texinfo"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ texinfo_install_user }}"
          group: "{{ texinfo_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ texinfo_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ texinfo_app_dir }}"
          - "{{ texinfo_base_dir }}"

- name: "mkdir {{ texinfo_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ texinfo_install_user }}"
          group: "{{ texinfo_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ texinfo_source_dir }}"
  when: texinfo_deploy_mode == "source"
