---
# tasks file for coreutils
# delete coreutils_source_dir coreutils_app_dir

- name: "delete {{ coreutils_source_dir }} {{ coreutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ coreutils_source_dir }}"
      - "{{ coreutils_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ coreutils_install_user }}"
      group: "{{ coreutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ coreutils_dir }} {{ coreutils_app_base_dir }} {{ coreutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ coreutils_install_user }}"
      group: "{{ coreutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ coreutils_dir }}"
      - "{{ coreutils_app_base_dir }}"
      - "{{ coreutils_app_dir }}"
  when:
      - coreutils_deploy_method == "binary" or coreutils_deploy_method == "source"

# source dir
- name: "mkdir {{ coreutils_dir }} {{ coreutils_source_base_dir }}  {{ coreutils_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ coreutils_install_user }}"
      group: "{{ coreutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ coreutils_source_base_dir }}"
      - "{{ coreutils_source_dir }}"
  when:
      - coreutils_deploy_method == "source"

# service dir
- name: "mkdir {{ coreutils_data_dir }} {{ coreutils_conf_dir }} {{ coreutils_log_dir }} {{ coreutils_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ coreutils_install_user }}"
      group: "{{ coreutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ coreutils_data_dir }}"
      - "{{ coreutils_conf_dir }}"
      - "{{ coreutils_log_dir }}"
      - "{{ coreutils_tmp_dir }}"
  when:
      - coreutils_port is defined
