---
# tasks file for coreutils by source
- name: "chown -R {{  coreutils_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ coreutils_install_user }}.{{ coreutils_install_group }} {{  coreutils_dir  }}"

# source
- name: "coreutils_deploy_method == 'source'"
  block:
      - name: "cd {{ coreutils_source_dir }};./configure --prefix={{ coreutils_app_dir }}"
        shell:
            chdir: "{{ coreutils_source_dir }}"
            cmd: "./configure --prefix={{ coreutils_app_dir }}"
      - name: "cd {{ coreutils_source_dir }};make -j{{ ansible_processor_vcpus }}"
        shell:
            chdir: "{{ coreutils_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ coreutils_source_dir }};make install"
        shell:
            chdir: "{{ coreutils_source_dir }}"
            cmd: make install
  when: coreutils_deploy_method == "source"

# coreutils_port standalone
- name: coreutils_port is defined
  block:
      - name: "cd {{ coreutils_source_dir }};./configure --prefix={{ coreutils_base_dir }}"
        become: true
        shell:
            chdir: "{{ coreutils_source_dir }}"
            cmd: "./configure --prefix={{ coreutils_base_dir }}"
      - name: "cd {{ coreutils_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ coreutils_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ coreutils_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ coreutils_source_dir }}"
            cmd: make install
  when:
      - coreutils_port is defined
      - coreutils_deploy_mode == "standalone"

# chown
- name: "chown -R {{  coreutils_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ coreutils_install_user }}.{{ coreutils_install_group }} {{  coreutils_dir  }}"
