---
# defaults file for readline
# https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
# https://ftp.gnu.org/gnu/bash/readline-5.1.tar.gz
# https://mirrors.tuna.tsinghua.edu.cn/gnu/readline/readline-8.2.tar.gz
# DONE

# user
readline_install_user: "{{ ansible_user }}"
readline_install_group: "{{ ansible_user }}"
readline_version: "5.1"
# readline_port: "8032"

# standalone/cluster/pseudo_cluster
readline_deploy_mode: "standalone"

# binary/source/rpm/yum/dnf
readline_deploy_method: "source"

# url
readline_base_url: "https://mirrors.tuna.tsinghua.edu.cn/gnu/readline"
readline_base_url_remote: "https://ftp.gnu.org/gnu/readline"

# package
readline_package_suffix: ".tar.gz"
readline_package_name_rpm: "readline-{{ readline_version }}.rpm"
readline_package_name_binary: "readline-{{ readline_version }}-{{ ansible_architecture }}{{ readline_package_suffix }}"
readline_package_name_source: "readline-{{ readline_version }}{{ readline_package_suffix }}"
readline_package_name: "{% if readline_deploy_method == 'rpm' %}{{ readline_package_name_rpm }}{% elif readline_deploy_method == 'binary' %}{{ readline_package_name_binary }}{% elif readline_deploy_method == 'source' %}{{ readline_package_name_source }}{% else %}{{ readline_package_name_source }}{% endif %}"

# 一台机器上部署相同服务时，通过不同端口号和不同的base_dir来区分是最佳的，这样不用修改目录结构
# 1. 通过变更base_dir和端口
# /data
# /data/readline
# /data/readline/data
# /data/readline/conf
# /data/readline/log
# /data/readline/tmp
# /data/readline/source
# /data/readline/app
# /data/readline/app/readline-2.44
# /data/readline/app/readline-2.44/bin
# /data/readline/app/readline-2.44/lib
# /data/readline/app/readline-2.44/lib/pkgconfig
# /data/readline/app/readline-2.44/include
# /data/readline/app/readline-2.44/share
# /data/readline/source/readline-2.44
readline_dir: "{{ base_dir }}/readline"
readline_data_dir: "{{ readline_dir }}/data"
readline_conf_dir: "{{ readline_dir }}/conf"
readline_log_dir: "{{ readline_dir }}/log"
readline_tmp_dir: "{{ readline_dir }}/tmp"
readline_app_base_dir: "{{ readline_dir }}/app"
readline_source_base_dir: "{{ readline_dir }}/source"
readline_app_dir: "{{ readline_app_base_dir }}/readline-{{ readline_version }}"
readline_bin_dir: "{{ readline_app_dir }}/bin"
readline_lib_dir: "{{ readline_app_dir }}/lib"
readline_include_dir: "{{ readline_app_dir }}/include"
readline_share_dir: "{{ readline_app_dir }}/share"
readline_pkgconfig_dir: "{{ readline_lib_dir }}/pkgconfig"
readline_source_dir: "{{ readline_source_base_dir }}/readline-{{ readline_version }}"
