---
# tasks file for libgcrypt
- name: "remove {{ libgcrypt_source_dir }} {{ libgcrypt_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ libgcrypt_source_dir }}"
          - "{{ libgcrypt_base_dir }}"

- name: "mkdir for libgcrypt"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ libgcrypt_install_user }}"
          group: "{{ libgcrypt_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ libgcrypt_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ libgcrypt_app_dir }}"
          - "{{ libgcrypt_base_dir }}"

- name: "mkdir {{ libgcrypt_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ libgcrypt_install_user }}"
          group: "{{ libgcrypt_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ libgcrypt_source_dir }}"
  when: libgcrypt_deploy_mode == "source"
