---
# tasks file for libgcrypt
# delete libgcrypt_source_dir libgcrypt_app_dir

- name: "delete {{ libgcrypt_source_dir }} {{ libgcrypt_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ libgcrypt_source_dir }}"
      - "{{ libgcrypt_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libgcrypt_install_user }}"
      group: "{{ libgcrypt_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ libgcrypt_dir }} {{ libgcrypt_app_base_dir }} {{ libgcrypt_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libgcrypt_install_user }}"
      group: "{{ libgcrypt_install_group }}"
      mode: 0755
  with_items:
      - "{{ libgcrypt_dir }}"
      - "{{ libgcrypt_app_base_dir }}"
      - "{{ libgcrypt_app_dir }}"
  when:
      - libgcrypt_deploy_method == "binary" or libgcrypt_deploy_method == "source"

# source dir
- name: "mkdir {{ libgcrypt_dir }} {{ libgcrypt_source_base_dir }}  {{ libgcrypt_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libgcrypt_install_user }}"
      group: "{{ libgcrypt_install_group }}"
      mode: 0755
  with_items:
      - "{{ libgcrypt_source_base_dir }}"
      - "{{ libgcrypt_source_dir }}"
  when:
      - libgcrypt_deploy_method == "source"

# service dir
- name: "mkdir {{ libgcrypt_data_dir }} {{ libgcrypt_conf_dir }} {{ libgcrypt_log_dir }} {{ libgcrypt_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libgcrypt_install_user }}"
      group: "{{ libgcrypt_install_group }}"
      mode: 0755
  with_items:
      - "{{ libgcrypt_data_dir }}"
      - "{{ libgcrypt_conf_dir }}"
      - "{{ libgcrypt_log_dir }}"
      - "{{ libgcrypt_tmp_dir }}"
  when:
      - libgcrypt_port is defined
