---
# defaults file for openssl
# https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1w.tar.gz
openssl_install_user: "{{ ansible_user }}"
openssl_install_group: "{{ ansible_user }}"
openssl_version: "1.1.1w"
openssl_base_url: "{{ base_url }}"
openssl_base_url_remote: "https://github.com/openssl/openssl/archive/refs/tags"

# binary/source

openssl_deploy_mode: "source"
openssl_package_suffix: ".tar.gz"
openssl_package_name_binary: "openssl-{{ openssl_version }}"
openssl_package_name_source: "openssl-{{ openssl_version }}"

openssl_dir: "{{ base_dir }}/openssl"
openssl_app_dir: "{{ base_dir }}/openssl/app"
openssl_base_dir: "{{ openssl_app_dir }}/openssl-{{ openssl_version }}"
openssl_source_dir: "{{ openssl_app_dir }}/source/openssl-{{ openssl_version }}"
