---
# tasks file for mysql

- name: "date '+%Y%m%dT%H%M%S'"
  become: true
  shell:
      cmd: "date '+%Y%m%dT%H%M%S'"
  register: date_output

# check mysql_port
- name: "lsof -i:{{ mysql_port }}"
  become: true
  shell:
      cmd: "lsof -i:{{ mysql_port }}"
  register: mysql_port_check_output
  ignore_errors: true
  when: mysql_port is defined

- name: "check mysql port"
  become: true
  fail:
      msg: "mysqld端口被占用,可使用: ps aux|grep mysqld"
  when:
      - mysql_port is defined
      - mysql_port_check_output is defined
      - mysql_port_check_output.rc == 0
