---
# tasks file for gmp

- name: "date '+%Y%m%dT%H%M%S'"
  become: true
  shell:
      cmd: "date '+%Y%m%dT%H%M%S'"
  register: date_output

# check gmp_port
- name: "lsof -i:{{ gmp_port }}"
  become: true
  shell:
      cmd: "lsof -i:{{ gmp_port }}"
  register: gmp_port_check_output
  ignore_errors: true
  when: gmp_port is defined

- name: "check gmp port"
  become: true
  fail:
      msg: "gmpd端口被占用,可使用: ps aux|grep gmpd"
  when:
      - gmp_port is defined
      - gmp_port_check_output is defined
      - gmp_port_check_output.rc == 0
