---
# tasks file for gmp
# delete gmp_source_dir gmp_app_dir

- name: "delete {{ gmp_source_dir }} {{ gmp_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ gmp_source_dir }}"
      - "{{ gmp_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gmp_install_user }}"
      group: "{{ gmp_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ gmp_dir }} {{ gmp_app_base_dir }} {{ gmp_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gmp_install_user }}"
      group: "{{ gmp_install_group }}"
      mode: 0755
  with_items:
      - "{{ gmp_dir }}"
      - "{{ gmp_app_base_dir }}"
      - "{{ gmp_app_dir }}"
  when:
      - gmp_deploy_method == "binary" or gmp_deploy_method == "source"

# source dir
- name: "mkdir {{ gmp_dir }} {{ gmp_source_base_dir }}  {{ gmp_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gmp_install_user }}"
      group: "{{ gmp_install_group }}"
      mode: 0755
  with_items:
      - "{{ gmp_source_base_dir }}"
      - "{{ gmp_source_dir }}"
  when:
      - gmp_deploy_method == "source"

# service dir
- name: "mkdir {{ gmp_data_dir }} {{ gmp_conf_dir }} {{ gmp_log_dir }} {{ gmp_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gmp_install_user }}"
      group: "{{ gmp_install_group }}"
      mode: 0755
  with_items:
      - "{{ gmp_data_dir }}"
      - "{{ gmp_conf_dir }}"
      - "{{ gmp_log_dir }}"
      - "{{ gmp_tmp_dir }}"
  when:
      - gmp_port is defined
