---
# tasks file for gmp
- name: "remove {{ gmp_source_dir }} {{ gmp_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ gmp_source_dir }}"
          - "{{ gmp_base_dir }}"

- name: "mkdir for gmp"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ gmp_install_user }}"
          group: "{{ gmp_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ gmp_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ gmp_app_dir }}"
          - "{{ gmp_base_dir }}"

- name: "mkdir {{ gmp_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ gmp_install_user }}"
          group: "{{ gmp_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ gmp_source_dir }}"
  when: gmp_deploy_method == "source"
