---
# tasks file for gmp by source
- name: "chown -R {{  gmp_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ gmp_install_user }}.{{ gmp_install_group }} {{  gmp_dir  }}"

# source
- name: "gmp_deploy_method == 'source'"
  block:
      - name: "cd {{ gmp_source_dir }};./configure --prefix={{ gmp_app_dir }}"
        shell:
            chdir: "{{ gmp_source_dir }}"
            cmd: "./configure --prefix={{ gmp_app_dir }}"
      - name: "cd {{ gmp_source_dir }};make -j{{ ansible_processor_vcpus }}"
        shell:
            chdir: "{{ gmp_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ gmp_source_dir }};make install"
        shell:
            chdir: "{{ gmp_source_dir }}"
            cmd: make install
  when: gmp_deploy_method == "source"

# gmp_port standalone
- name: gmp_port is defined
  block:
      - name: "cd {{ gmp_source_dir }};./configure --prefix={{ gmp_base_dir }}"
        become: true
        shell:
            chdir: "{{ gmp_source_dir }}"
            cmd: "./configure --prefix={{ gmp_base_dir }}"
      - name: "cd {{ gmp_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ gmp_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ gmp_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ gmp_source_dir }}"
            cmd: make install
  when:
      - gmp_port is defined
      - gmp_deploy_mode == "standalone"

# chown
- name: "chown -R {{  gmp_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ gmp_install_user }}.{{ gmp_install_group }} {{  gmp_dir  }}"
