---
# tasks file for jdk
- name: "remove {{ jdk_source_dir }} {{ jdk_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ jdk_source_dir }}"
          - "{{ jdk_base_dir }}"

- name: "mkdir for jdk"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ jdk_install_user }}"
          group: "{{ jdk_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ jdk_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ jdk_app_dir }}"
          - "{{ jdk_base_dir }}"

- name: "mkdir {{ jdk_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ jdk_install_user }}"
          group: "{{ jdk_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ jdk_source_dir }}"
  when: jdk_deploy_method == "source"
