---
# tasks file for jdk

# delete old JAVA_HOME from  ~/.bashrc
- name: "delete old JAVA_HOME from  ~/.bashrc"
  become: true
  lineinfile:
      dest: ~/.bashrc
      regex: "^.*JAVA_HOME.*$"
      state: absent

# add JAVA_HOME PATH  JRE_HOME  CLASSPATH to  ~/.bashrc
- name: "add JAVA_HOME to  ~/.bashrc"
  become: true
  lineinfile:
      dest: ~/.bashrc
      line: "{{item}}"
  loop:
      - export JAVA_HOME="{{jdk_base_dir}}"
      - export JRE_HOME="$JAVA_HOME/jre"
      - export CLASSPATH=".:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH"
      - export PATH="$JAVA_HOME/bin:$PATH"
