---
# tasks file for work_jdk
- include_tasks: 01-dir.yml

# install
- name: "02-install_binary.yml"
  include_tasks: 02-install_binary.yml
  when: jdk_deploy_method == "binary"

- name: "02-install_source.yml"
  include_tasks: 02-install_source.yml
  when: jdk_deploy_method == "source"

# init
- name: "03-init_binary.yml"
  include_tasks: 03-init_binary.yml
  when: jdk_deploy_method == "binary"

- name: "03-init_source.yml"
  include_tasks: 03-init_source.yml
  when: jdk_deploy_method == "source"
