---
# tasks file for cmake
- name: "remove {{cmake_source_dir}} {{cmake_base_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: absent
  with_items:
      - "{{cmake_source_dir}}"
      - "{{cmake_base_dir}}"

- name: "mkdir for cmake"
  become: true
  file:
      path: "{{item}}"
      state: directory
      owner: "{{cmake_install_user}}"
      group: "{{cmake_install_group}}"
      mode: 0755
  with_items:
      - "{{base_dir}}"
      - "{{cmake_dir}}"
      - "{{install_tmpdir}}"
      - "{{cmake_app_dir}}"
      - "{{cmake_base_dir}}"

- name: "mkdir {{cmake_source_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: "{{cmake_install_user}}"
      group: "{{cmake_install_group}}"
  with_items:
      - "{{base_dir}}"
      - "{{cmake_source_dir}}"
  when: cmake_deploy_method == "source"
