---

- name: Create base_dir tmpdir directory
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  when: 
    - install_tmpdir is defined
    - base_dir is defined
  loop:
    - "{{ base_dir }}"
    - "{{ install_tmpdir }}"

