---
- name: disable UFW (Kylin)
  become: True
  ufw:
      state: disabled
      policy: allow
  when: ansible_os_family == 'Kylin'

- name: Check if firewalld is installed (Red Hat)
  command: rpm -q firewalld
  register: firewalld_check
  changed_when: false
  failed_when: firewalld_check.rc > 1
  args:
      warn: false
  when: ansible_os_family == 'RedHat'

- name: Disable firewalld (Red Hat)
  become: True
  service:
      name: "{{item}}"
      enabled: false
      state: stopped
  with_items:
      - firewalld
  when:
      - ansible_os_family == 'RedHat'
      - firewalld_check.rc == 0
