---
# tasks file for shadow

- name: "date '+%Y%m%dT%H%M%S'"
  become: true
  shell:
      cmd: "date '+%Y%m%dT%H%M%S'"
  register: date_output

# check shadow_port
- name: "lsof -i:{{ shadow_port }}"
  become: true
  shell:
      cmd: "lsof -i:{{ shadow_port }}"
  register: shadow_port_check_output
  ignore_errors: true
  when: shadow_port is defined

- name: "check shadow port"
  become: true
  fail:
      msg: "shadowd端口被占用,可使用: ps aux|grep shadowd"
  when:
      - shadow_port is defined
      - shadow_port_check_output is defined
      - shadow_port_check_output.rc == 0
