---
# defaults file for isl
# https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2

# user
isl_install_user: "{{ ansible_user }}"
isl_install_group: "{{ ansible_user }}"
isl_version: "0.18"
# isl_port: "8032"

# standalone/cluster/pseudo_cluster
isl_deploy_mode: "standalone"

# binary/source/rpm/yum/dnf
isl_deploy_method: "source"

# url
isl_base_url: "{{ base_url }}"
isl_base_url_remote: "https://gcc.gnu.org/pub/gcc/infrastructure"

# package
isl_package_suffix: ".tar.bz2"
isl_package_name_rpm: "isl-{{ isl_version }}.rpm"
isl_package_name_binary: "isl-{{ isl_version }}-{{ ansible_architecture }}{{ isl_package_suffix }}"
isl_package_name_source: "isl-{{ isl_version }}{{ isl_package_suffix }}"
isl_package_name: "{% if isl_deploy_method == 'rpm' %}{{ isl_package_name_rpm }}{% elif isl_deploy_method == 'binary' %}{{ isl_package_name_binary }}{% elif isl_deploy_method == 'source' %}{{ isl_package_name_source }}{% else %}{{ isl_package_name_source }}{% endif %}"

# 一台机器上部署相同服务时，通过不同端口号和不同的base_dir来区分是最佳的，这样不用修改目录结构
# 1. 通过变更base_dir和端口
# /data
# /data/isl
# /data/isl/data
# /data/isl/conf
# /data/isl/log
# /data/isl/tmp
# /data/isl/source
# /data/isl/app
# /data/isl/app/isl-2.44
# /data/isl/app/isl-2.44/bin
# /data/isl/app/isl-2.44/lib
# /data/isl/app/isl-2.44/lib/pkgconfig
# /data/isl/app/isl-2.44/include
# /data/isl/app/isl-2.44/share
# /data/isl/source/isl-2.44
isl_dir: "{{ base_dir }}/isl"
isl_data_dir: "{{ isl_dir }}/data"
isl_conf_dir: "{{ isl_dir }}/conf"
isl_log_dir: "{{ isl_dir }}/log"
isl_tmp_dir: "{{ isl_dir }}/tmp"
isl_app_base_dir: "{{ isl_dir }}/app"
isl_source_base_dir: "{{ isl_dir }}/source"
isl_app_dir: "{{ isl_app_base_dir }}/isl-{{ isl_version }}"
isl_bin_dir: "{{ isl_app_dir }}/bin"
isl_lib_dir: "{{ isl_app_dir }}/lib"
isl_include_dir: "{{ isl_app_dir }}/include"
isl_share_dir: "{{ isl_app_dir }}/share"
isl_pkgconfig_dir: "{{ isl_lib_dir }}/pkgconfig"
isl_source_dir: "{{ isl_source_base_dir }}/isl-{{ isl_version }}"
