---
# tasks file for less
# delete less_source_dir less_app_dir

- name: "delete {{ less_source_dir }} {{ less_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ less_source_dir }}"
      - "{{ less_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ less_install_user }}"
      group: "{{ less_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ less_dir }} {{ less_app_base_dir }} {{ less_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ less_install_user }}"
      group: "{{ less_install_group }}"
      mode: 0755
  with_items:
      - "{{ less_dir }}"
      - "{{ less_app_base_dir }}"
      - "{{ less_app_dir }}"
  when:
      - less_deploy_method == "binary" or less_deploy_method == "source"

# source dir
- name: "mkdir {{ less_dir }} {{ less_source_base_dir }}  {{ less_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ less_install_user }}"
      group: "{{ less_install_group }}"
      mode: 0755
  with_items:
      - "{{ less_source_base_dir }}"
      - "{{ less_source_dir }}"
  when:
      - less_deploy_method == "source"

# service dir
- name: "mkdir {{ less_data_dir }} {{ less_conf_dir }} {{ less_log_dir }} {{ less_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ less_install_user }}"
      group: "{{ less_install_group }}"
      mode: 0755
  with_items:
      - "{{ less_data_dir }}"
      - "{{ less_conf_dir }}"
      - "{{ less_log_dir }}"
      - "{{ less_tmp_dir }}"
  when:
      - less_port is defined
