---
# bin
- name: "Extract {{ install_tmpdir }}/prometheus-{{ prometheus_version }}"
  become: true
  unarchive:
    src: "{{ install_tmpdir }}/mysql-{{ mysql_version }}-{{ ansible_architecture }}.tar.gz"
    dest: "{{ mysql_base_dir }}/"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    extra_opts:
      - --strip-components=1
    exclude:
      - "*.md"
      - "Document*"
  when: mysql_deploy_mode == "bin"

# source
- name: "Extract {{ install_tmpdir }}/prometheus-{{ prometheus_version }}"
  become: true
  unarchive:
    src: "{{ install_tmpdir }}/mysql-{{ mysql_version }}.tar.gz"
    dest: "{{ mysql_source_dir }}/"
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    extra_opts:
      - --strip-components=1
    exclude:
      - "*.md"
      - "Document*"
  when: mysql_deploy_mode == "source"

