---
# tasks file for mysql

- name: remove PS1 from /etc/profile
  become: yes
  lineinfile:
    path: /etc/profile
    regexp: '^PS1'
    state: absent

- name: Add PS1 to /etc/profile
  become: yes
  lineinfile:
    path: /etc/profile
    line: "PS1={{ PS1 }}"
    #line: 'PS1="\[\033[01;37m\]\D{\%Y-\%m-\%d}T\t "'
    insertafter: EOF
    state: present

- name: remove MYSQL_PS1 from /etc/profile
  become: yes
  lineinfile:
    path: /etc/profile
    regexp: 'MYSQL_PS1'
    state: absent

- name: Add MYSQL_PS1 to /etc/profile
  become: yes
  lineinfile:
    path: /etc/profile
    line: 'export MYSQL_PS1="[\\U \\R:\\m:\\s(\\d)]$"'
    insertafter: EOF
    state: present
