---
# tasks file for guile
- name: "remove {{guile_source_dir}} {{guile_base_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: absent
  with_items:
      - "{{guile_source_dir}}"
      - "{{guile_base_dir}}"

- name: "mkdir for guile"
  become: true
  file:
      path: "{{item}}"
      state: directory
      owner: "{{guile_install_user}}"
      group: "{{guile_install_group}}"
      mode: 0755
  with_items:
      - "{{base_dir}}"
      - "{{guile_dir}}"
      - "{{install_tmpdir}}"
      - "{{guile_app_dir}}"
      - "{{guile_base_dir}}"

- name: "mkdir {{guile_source_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: "{{guile_install_user}}"
      group: "{{guile_install_group}}"
  with_items:
      - "{{base_dir}}"
      - "{{guile_source_dir}}"
  when: guile_deploy_method == "source"
