---
# tasks file for clang by source

# 检查远程主机上的文件是否存在
# 检查远程主机上的文件是否完整
- name: "Check file exists first"
  stat:
      path: "{{install_tmpdir}}/{{clang_package_name_source}}"
  register: check_file_exists_first

- name: "Check file valid first"
  command: "gzip -t {{install_tmpdir}}/{{clang_package_name_source}}"
  register: check_file_valid_first
  ignore_errors: true
  when: check_file_exists_first.stat.exists

############################################
# 从控制机拷贝
############################################
- name: "Check file exists on ansible host"
  delegate_to: localhost
  run_once: true
  stat:
      path: "{{role_path}}/files/{{clang_package_name_source}}"
  register: local_file_stat

- name: "Copy file from control machine if remote file is missing or invalid"
  become: true
  copy:
      src: "{{clang_package_name_source}}"
      dest: "{{install_tmpdir}}/"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0755
  when:
      - (not check_file_exists_first.stat.exists or check_file_valid_first.rc != 0)
      - local_file_stat.stat.exists

#################################################
# 从 clang_base_url 下载
#################################################

- name: "Check file exists second"
  stat:
      path: "{{install_tmpdir}}/{{clang_package_name_source}}"
  register: check_file_exists_second

- name: "Check file valid second"
  command: "gzip -t {{install_tmpdir}}/{{clang_package_name_source}}"
  register: check_file_valid_second
  ignore_errors: true
  when: check_file_exists_second.stat.exists

- name: "Download file from clang_base_url if remote file is missing or invalid"
  get_url:
      url: "{{clang_base_url}}/{{clang_package_name_source}}"
      dest: "{{install_tmpdir}}/{{clang_package_name_source}}"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0755
      timeout: 600
  when:
      - (not check_file_exists_second.stat.exists or check_file_valid_second.rc != 0)
  ignore_errors: true

#################################################
# 尝试从 clang_base_url_remote 下载
#################################################

- name: "Check file exists third"
  stat:
      path: "{{install_tmpdir}}/{{clang_package_name_source}}"
  register: check_file_exists_third

- name: "Check file valid third"
  command: "gzip -t {{install_tmpdir}}/{{clang_package_name_source}}"
  register: check_file_valid_third
  ignore_errors: true
  when: check_file_exists_third.stat.exists

- name: "Download file from clang_base_url_remote if previous download failed"
  get_url:
      url: "{{clang_base_url_remote}}/llvmorg-{{clang_version}}{{clang_package_suffix}}"
      dest: "{{install_tmpdir}}/{{clang_package_name_source}}"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0755
      timeout: 600
  when:
      - (not check_file_exists_third.stat.exists or check_file_valid_third.rc != 0)

#################################################
# 如果部署模式为源码编译，则解压并安装
#################################################
- name: "Extract {{install_tmpdir}}/{{clang_package_name_source}}"
  become: true
  unarchive:
      src: "{{install_tmpdir}}/{{clang_package_name_source}}"
      dest: "{{clang_source_dir}}/"
      remote_src: true
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      extra_opts:
          - --strip-components=1

- name: "mkdir {{clang_source_dir}}/build"
  become: true
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: "{{clang_install_user}}"
      group: "{{clang_install_group}}"
  with_items:
      - "{{clang_source_dir}}/build"

- name: "cmake3 -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX={{clang_base_dir}} -DCMAKE_BUILD_TYPE=Release  ../clang"
  become: true
  shell:
      chdir: "{{clang_source_dir}}/build"
      cmd: "cmake3 -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX={{clang_base_dir}} -DCMAKE_BUILD_TYPE=Release  ../clang"

- name: "make"
  become: true
  shell:
      chdir: "{{clang_source_dir}}/build"
      cmd: "make -j{{ansible_processor_vcpus}}"

- name: "make install"
  become: true
  shell:
      chdir: "{{clang_source_dir}}/build"
      cmd: make install
