---
# tasks file for m4
- name: "remove {{ m4_source_dir }} {{ m4_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ m4_source_dir }}"
          - "{{ m4_base_dir }}"

- name: "mkdir for m4"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ m4_install_user }}"
          group: "{{ m4_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ m4_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ m4_app_dir }}"
          - "{{ m4_base_dir }}"

- name: "mkdir {{ m4_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ m4_install_user }}"
          group: "{{ m4_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ m4_source_dir }}"
  when: m4_deploy_mode == "source"
