---
# tasks file for m4
# delete m4_source_dir m4_app_dir

- name: "delete {{ m4_source_dir }} {{ m4_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ m4_source_dir }}"
      - "{{ m4_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ m4_install_user }}"
      group: "{{ m4_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ m4_dir }} {{ m4_app_base_dir }} {{ m4_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ m4_install_user }}"
      group: "{{ m4_install_group }}"
      mode: 0755
  with_items:
      - "{{ m4_dir }}"
      - "{{ m4_app_base_dir }}"
      - "{{ m4_app_dir }}"
  when:
      - m4_deploy_method == "binary" or m4_deploy_method == "source"

# source dir
- name: "mkdir {{ m4_dir }} {{ m4_source_base_dir }}  {{ m4_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ m4_install_user }}"
      group: "{{ m4_install_group }}"
      mode: 0755
  with_items:
      - "{{ m4_source_base_dir }}"
      - "{{ m4_source_dir }}"
  when:
      - m4_deploy_method == "source"

# service dir
- name: "mkdir {{ m4_data_dir }} {{ m4_conf_dir }} {{ m4_log_dir }} {{ m4_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ m4_install_user }}"
      group: "{{ m4_install_group }}"
      mode: 0755
  with_items:
      - "{{ m4_data_dir }}"
      - "{{ m4_conf_dir }}"
      - "{{ m4_log_dir }}"
      - "{{ m4_tmp_dir }}"
  when:
      - m4_port is defined
