---
# tasks file for libunistring
- name: "remove {{ libunistring_source_dir }} {{ libunistring_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ libunistring_source_dir }}"
          - "{{ libunistring_base_dir }}"

- name: "mkdir for libunistring"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ libunistring_install_user }}"
          group: "{{ libunistring_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ libunistring_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ libunistring_app_dir }}"
          - "{{ libunistring_base_dir }}"

- name: "mkdir {{ libunistring_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ libunistring_install_user }}"
          group: "{{ libunistring_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ libunistring_source_dir }}"
  when: libunistring_deploy_mode == "source"
