---
# tasks file for libunistring
# delete libunistring_source_dir libunistring_app_dir

- name: "delete {{ libunistring_source_dir }} {{ libunistring_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ libunistring_source_dir }}"
      - "{{ libunistring_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libunistring_install_user }}"
      group: "{{ libunistring_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ libunistring_dir }} {{ libunistring_app_base_dir }} {{ libunistring_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libunistring_install_user }}"
      group: "{{ libunistring_install_group }}"
      mode: 0755
  with_items:
      - "{{ libunistring_dir }}"
      - "{{ libunistring_app_base_dir }}"
      - "{{ libunistring_app_dir }}"
  when:
      - libunistring_deploy_method == "binary" or libunistring_deploy_method == "source"

# source dir
- name: "mkdir {{ libunistring_dir }} {{ libunistring_source_base_dir }}  {{ libunistring_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libunistring_install_user }}"
      group: "{{ libunistring_install_group }}"
      mode: 0755
  with_items:
      - "{{ libunistring_source_base_dir }}"
      - "{{ libunistring_source_dir }}"
  when:
      - libunistring_deploy_method == "source"

# service dir
- name: "mkdir {{ libunistring_data_dir }} {{ libunistring_conf_dir }} {{ libunistring_log_dir }} {{ libunistring_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libunistring_install_user }}"
      group: "{{ libunistring_install_group }}"
      mode: 0755
  with_items:
      - "{{ libunistring_data_dir }}"
      - "{{ libunistring_conf_dir }}"
      - "{{ libunistring_log_dir }}"
      - "{{ libunistring_tmp_dir }}"
  when:
      - libunistring_port is defined
