---
# tasks file for work_mysql

- include_tasks: 00-check.yml
- include_tasks: 01-dir.yml

- name: "02-install_binary.yml"
  include_tasks: 02-install_binary.yml
  when: mysql_deploy_method == "binary"

- name: "02-install_source.yml"
  include_tasks: 02-install_source.yml
  when: mysql_deploy_method == "source"

- include_tasks: 03-init.yml
