---
# tasks file for grep

- name: "date '+%Y%m%dT%H%M%S'"
  become: true
  shell:
      cmd: "date '+%Y%m%dT%H%M%S'"
  register: date_output

# check grep_port
- name: "lsof -i:{{ grep_port }}"
  become: true
  shell:
      cmd: "lsof -i:{{ grep_port }}"
  register: grep_port_check_output
  ignore_errors: true
  when: grep_port is defined

- name: "check grep port"
  become: true
  fail:
      msg: "grepd端口被占用,可使用: ps aux|grep grepd"
  when:
      - grep_port is defined
      - grep_port_check_output is defined
      - grep_port_check_output.rc == 0
