---
# tasks file for grep
# delete grep_source_dir grep_app_dir

- name: "delete {{ grep_source_dir }} {{ grep_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ grep_source_dir }}"
      - "{{ grep_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grep_install_user }}"
      group: "{{ grep_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ grep_dir }} {{ grep_app_base_dir }} {{ grep_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grep_install_user }}"
      group: "{{ grep_install_group }}"
      mode: 0755
  with_items:
      - "{{ grep_dir }}"
      - "{{ grep_app_base_dir }}"
      - "{{ grep_app_dir }}"
  when:
      - grep_deploy_method == "binary" or grep_deploy_method == "source"

# source dir
- name: "mkdir {{ grep_dir }} {{ grep_source_base_dir }}  {{ grep_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grep_install_user }}"
      group: "{{ grep_install_group }}"
      mode: 0755
  with_items:
      - "{{ grep_source_base_dir }}"
      - "{{ grep_source_dir }}"
  when:
      - grep_deploy_method == "source"

# service dir
- name: "mkdir {{ grep_data_dir }} {{ grep_conf_dir }} {{ grep_log_dir }} {{ grep_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grep_install_user }}"
      group: "{{ grep_install_group }}"
      mode: 0755
  with_items:
      - "{{ grep_data_dir }}"
      - "{{ grep_conf_dir }}"
      - "{{ grep_log_dir }}"
      - "{{ grep_tmp_dir }}"
  when:
      - grep_port is defined
