---
# tasks file for gperf
- name: "remove {{ gperf_source_dir }} {{ gperf_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ gperf_source_dir }}"
          - "{{ gperf_base_dir }}"

- name: "mkdir for gperf"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ gperf_install_user }}"
          group: "{{ gperf_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ gperf_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ gperf_app_dir }}"
          - "{{ gperf_base_dir }}"

- name: "mkdir {{ gperf_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ gperf_install_user }}"
          group: "{{ gperf_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ gperf_source_dir }}"
  when: gperf_deploy_method == "source"
