---
# tasks file for gperf
# delete gperf_source_dir gperf_app_dir

- name: "delete {{ gperf_source_dir }} {{ gperf_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ gperf_source_dir }}"
      - "{{ gperf_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gperf_install_user }}"
      group: "{{ gperf_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ gperf_dir }} {{ gperf_app_base_dir }} {{ gperf_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gperf_install_user }}"
      group: "{{ gperf_install_group }}"
      mode: 0755
  with_items:
      - "{{ gperf_dir }}"
      - "{{ gperf_app_base_dir }}"
      - "{{ gperf_app_dir }}"
  when:
      - gperf_deploy_method == "binary" or gperf_deploy_method == "source"

# source dir
- name: "mkdir {{ gperf_dir }} {{ gperf_source_base_dir }}  {{ gperf_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gperf_install_user }}"
      group: "{{ gperf_install_group }}"
      mode: 0755
  with_items:
      - "{{ gperf_source_base_dir }}"
      - "{{ gperf_source_dir }}"
  when:
      - gperf_deploy_method == "source"

# service dir
- name: "mkdir {{ gperf_data_dir }} {{ gperf_conf_dir }} {{ gperf_log_dir }} {{ gperf_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gperf_install_user }}"
      group: "{{ gperf_install_group }}"
      mode: 0755
  with_items:
      - "{{ gperf_data_dir }}"
      - "{{ gperf_conf_dir }}"
      - "{{ gperf_log_dir }}"
      - "{{ gperf_tmp_dir }}"
  when:
      - gperf_port is defined
