---
# tasks file for libaio
- name: "remove {{libaio_source_dir}} {{libaio_base_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: absent
  with_items:
      - "{{libaio_source_dir}}"
      - "{{libaio_base_dir}}"

- name: "mkdir for libaio"
  become: true
  file:
      path: "{{item}}"
      state: directory
      owner: "{{libaio_install_user}}"
      group: "{{libaio_install_group}}"
      mode: 0755
  with_items:
      - "{{base_dir}}"
      - "{{libaio_dir}}"
      - "{{install_tmpdir}}"
      - "{{libaio_app_dir}}"
      - "{{libaio_base_dir}}"

- name: "mkdir {{libaio_source_dir}}"
  become: true
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      owner: "{{libaio_install_user}}"
      group: "{{libaio_install_group}}"
  with_items:
      - "{{base_dir}}"
      - "{{libaio_source_dir}}"
  when: libaio_deploy_method == "source"
