---
# bin
- name: "Extract {{ install_tmpdir }}/mysql-{{ mysql_version }}-{{ ansible_architecture }}.tar.gz"
  become: true
  unarchive:
          src: "{{ install_tmpdir }}/mysql-{{ mysql_version }}-{{ ansible_architecture }}.tar.gz"
          dest: "{{ mysql_base_dir }}/"
          remote_src: true
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          mode: 0755
          extra_opts:
                  - --strip-components=1
          exclude:
                  - "*.md"
                  - "Document*"
  when: mysql_deploy_mode == "bin"

# source
- name: "Extract {{ install_tmpdir }}/mysql-{{ mysql_version }}.tar.gz"
  become: true
  unarchive:
          src: "{{ install_tmpdir }}/mysql-{{ mysql_version }}.tar.gz"
          dest: "{{ mysql_source_dir }}/"
          remote_src: true
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          extra_opts:
                  - --strip-components=1
          exclude:
                  - "*.md"
                  - "Document*"
  when: mysql_deploy_mode == "source"
######################################
# CPATH
# C_INCLUDE_PATH
# CPLUS_INCLUDE_PATH

# LIBRARY_PATH
# LD_LIBRARY_PATH
# LD_RUN_PATH

# CC
# CXX
# CFLAGS
# CXXFLAGS

# LDFLAGS
# PKG_CONFIG_PATH
# CMAKE_INCLUDE_PATH
# CMAKE_LIBRARY_PATH

