---
# tasks file for readline
- name: "remove {{ readline_source_dir }} {{ readline_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ readline_source_dir }}"
          - "{{ readline_base_dir }}"

- name: "mkdir for readline"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ readline_install_user }}"
          group: "{{ readline_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ readline_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ readline_app_dir }}"
          - "{{ readline_base_dir }}"

- name: "mkdir {{ readline_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ readline_install_user }}"
          group: "{{ readline_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ readline_source_dir }}"
  when: readline_deploy_mode == "source"
