---
# tasks file for readline
# https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz

- include_tasks: 01-dir.yml

- name: "02-install_binary.yml"
  include_tasks: 02-install_binary.yml
  when: readline_deploy_method == "binary"

- name: "02-install_source.yml"
  include_tasks: 02-install_source.yml
  when: readline_deploy_method == "source"

- include_tasks: 03-init.yml
