---
# defaults file for zlib
# https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz
# DONE

# user
zlib_install_user: "{{ ansible_user }}"
zlib_install_group: "{{ ansible_user }}"
zlib_version: "1.3.1"
# zlib_port: "8032"

# standalone/cluster/pseudo_cluster
zlib_deploy_mode: "standalone"

# binary/source/rpm/yum/dnf
zlib_deploy_method: "source"

# url
zlib_base_url: "{{ base_url }}"
zlib_base_url_remote: "https://github.com/madler/zlib/archive/refs/tags"

# package
zlib_package_suffix: ".tar.gz"
zlib_package_name_rpm: "zlib-{{ zlib_version }}.rpm"
zlib_package_name_binary: "zlib-{{ zlib_version }}-{{ ansible_architecture }}{{ zlib_package_suffix }}"
zlib_package_name_source: "zlib-{{ zlib_version }}{{ zlib_package_suffix }}"
zlib_package_name: "{% if zlib_deploy_method == 'rpm' %}{{ zlib_package_name_rpm }}{% elif zlib_deploy_method == 'binary' %}{{ zlib_package_name_binary }}{% elif zlib_deploy_method == 'source' %}{{ zlib_package_name_source }}{% else %}{{ zlib_package_name_source }}{% endif %}"

# 一台机器上部署相同服务时，通过不同端口号和不同的base_dir来区分是最佳的，这样不用修改目录结构
# 1. 通过变更base_dir和端口
# /data
# /data/zlib
# /data/zlib/data
# /data/zlib/conf
# /data/zlib/log
# /data/zlib/tmp
# /data/zlib/source
# /data/zlib/app
# /data/zlib/app/zlib-{{ zlib_version }}
# /data/zlib/app/zlib-{{ zlib_version }}/bin
# /data/zlib/app/zlib-{{ zlib_version }}/lib
# /data/zlib/app/zlib-{{ zlib_version }}/lib/pkgconfig
# /data/zlib/app/zlib-{{ zlib_version }}/include
# /data/zlib/app/zlib-{{ zlib_version }}/share
# /data/zlib/source/zlib-{{ zlib_version }}
zlib_dir: "{{ base_dir }}/zlib"
zlib_data_dir: "{{ zlib_dir }}/data"
zlib_conf_dir: "{{ zlib_dir }}/conf"
zlib_log_dir: "{{ zlib_dir }}/log"
zlib_tmp_dir: "{{ zlib_dir }}/tmp"
zlib_app_base_dir: "{{ zlib_dir }}/app"
zlib_source_base_dir: "{{ zlib_dir }}/source"
zlib_app_dir: "{{ zlib_app_base_dir }}/zlib-{{ zlib_version }}"
zlib_bin_dir: "{{ zlib_app_dir }}/bin"
zlib_lib_dir: "{{ zlib_app_dir }}/lib"
zlib_include_dir: "{{ zlib_app_dir }}/include"
zlib_share_dir: "{{ zlib_app_dir }}/share"
zlib_pkgconfig_dir: "{{ zlib_lib_dir }}/pkgconfig"
zlib_source_dir: "{{ zlib_source_base_dir }}/zlib-{{ zlib_version }}"
zlib_build_dir: "{{ zlib_source_dir }}/build_{{ date_output.stdout }}"
