---
# defaults file for zlib
# https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz
# DONE
zlib_install_user: "{{ ansible_user }}"
zlib_install_group: "{{ ansible_user }}"
zlib_version: "1.3.1"
# binary/source
zlib_deploy_method: "source"
zlib_base_url: "{{ base_url }}"
zlib_base_url_remote: "https://github.com/madler/zlib/archive/refs/tags"

zlib_package_suffix: ".tar.gz"
zlib_package_name_binary: "zlib-{{ zlib_version }}-{{ ansible_architecture }}{{ zlib_package_suffix }}"
zlib_package_name_source: "zlib-{{ zlib_version }}{{ zlib_package_suffix }}"

zlib_dir: "{{ base_dir }}/zlib"
zlib_app_dir: "{{ base_dir }}/zlib/app"
zlib_base_dir: "{{ zlib_app_dir }}/zlib-{{ zlib_version }}"
zlib_source_dir: "{{ zlib_app_dir }}/source/zlib-{{ zlib_version }}"
