---
# defaults file for os
os_packages_remove:
        - "mariadb-libs"
        - "mariadb"

os_packages:
        - "epel-release"
        - "glibc-headers"
        - "yum-utils"
        - "net-tools"
        - "lrzsz"
        - "tree"
        - "gcc"
        - "gcc-c++"
        - "make"
        - "cmake3"
        - "autogen"
        - "automake"
        - "autoconf"
        - "libaio"
        - "libaio-devel"
        - "openssl"
        - "openssl-devel"
        - "gettext"
        - "gettext-devel"
        - "ncurses"
        - "ncurses-devel"
        - "guile"
        - "guile-devel"
        - "bison"
        - "binutils"
        - "diffutils"
        - "patch"
        - "m4"
        - "gperf"
        - "texinfo"
        - "tcl"
        - "tcl-devel"
        - "zlib"
        - "zlib-devel"
        - "libtirpc"
        - "libtirpc-devel"
        - "sphinx"
        - "zstd"
        - "perl-Data-Dumper"
        - "perl-JSON"
####
