---
# tasks file for binutils
# delete binutils_source_dir binutils_app_dir

- name: "delete {{ binutils_source_dir }} {{ binutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ binutils_source_dir }}"
      - "{{ binutils_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ binutils_install_user }}"
      group: "{{ binutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ binutils_dir }} {{ binutils_app_base_dir }} {{ binutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ binutils_install_user }}"
      group: "{{ binutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ binutils_dir }}"
      - "{{ binutils_app_base_dir }}"
      - "{{ binutils_app_dir }}"
  when:
      - binutils_deploy_method == "binary" or binutils_deploy_method == "source"

# source dir
- name: "mkdir {{ binutils_build_dir }} {{ binutils_source_base_dir }}  {{ binutils_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ binutils_install_user }}"
      group: "{{ binutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ binutils_source_base_dir }}"
      - "{{ binutils_source_dir }}"
      - "{{ binutils_build_dir }}"
  when:
      - binutils_deploy_method == "source"

# service dir
- name: "mkdir {{ binutils_data_dir }} {{ binutils_conf_dir }} {{ binutils_log_dir }} {{ binutils_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ binutils_install_user }}"
      group: "{{ binutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ binutils_data_dir }}"
      - "{{ binutils_conf_dir }}"
      - "{{ binutils_log_dir }}"
      - "{{ binutils_tmp_dir }}"
  when:
      - binutils_port is defined
