---
# tasks file for automake
- name: "remove {{ automake_source_dir }} {{ automake_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ automake_source_dir }}"
          - "{{ automake_base_dir }}"

- name: "mkdir for automake"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ automake_install_user }}"
          group: "{{ automake_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ automake_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ automake_app_dir }}"
          - "{{ automake_base_dir }}"

- name: "mkdir {{ automake_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ automake_install_user }}"
          group: "{{ automake_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ automake_source_dir }}"
  when: automake_deploy_mode == "source"
