---
# tasks file for binutils
# https://ftp.gnu.org/gnu/binutils/binutils-2.44.tar.gz

- include_tasks: 01-dir.yml

- name: "02-install_binary.yml"
  include_tasks: 02-install_binary.yml
  when: binutils_deploy_mode == "binary"

- name: "02-install_source.yml"
  include_tasks: 02-install_source.yml
  when: binutils_deploy_mode == "source"

- include_tasks: 03-init.yml
