---
# defaults file for bison
# https://ftp.gnu.org/gnu/bison/bison-3.8.tar.gz

# user
bison_install_user: "{{ ansible_user }}"
bison_install_group: "{{ ansible_user }}"
bison_version: "3.8.2"
# bison_port: "8032"

# standalone/cluster/pseudo_cluster
bison_deploy_mode: "standalone"

# binary/source/rpm/yum/dnf
bison_deploy_method: "source"

# url
bison_base_url: "{{ base_url }}"
bison_base_url_remote: "https://ftp.gnu.org/gnu/bison"

# package
bison_package_suffix: ".tar.gz"
bison_package_name_rpm: "bison-{{ bison_version }}.rpm"
bison_package_name_binary: "bison-{{ bison_version }}-{{ ansible_architecture }}{{ bison_package_suffix }}"
bison_package_name_source: "bison-{{ bison_version }}{{ bison_package_suffix }}"
bison_package_name: "{% if bison_deploy_method == 'rpm' %}{{ bison_package_name_rpm }}{% elif bison_deploy_method == 'binary' %}{{ bison_package_name_binary }}{% elif bison_deploy_method == 'source' %}{{ bison_package_name_source }}{% else %}{{ bison_package_name_source }}{% endif %}"

# 一台机器上部署相同服务时，通过不同端口号和不同的base_dir来区分是最佳的，这样不用修改目录结构
# 1. 通过变更base_dir和端口
# /data
# /data/bison
# /data/bison/data
# /data/bison/conf
# /data/bison/log
# /data/bison/tmp
# /data/bison/source
# /data/bison/app
# /data/bison/app/bison-2.44
# /data/bison/app/bison-2.44/bin
# /data/bison/app/bison-2.44/lib
# /data/bison/app/bison-2.44/lib/pkgconfig
# /data/bison/app/bison-2.44/include
# /data/bison/app/bison-2.44/share
# /data/bison/source/bison-2.44
bison_dir: "{{ base_dir }}/bison"
bison_data_dir: "{{ bison_dir }}/data"
bison_conf_dir: "{{ bison_dir }}/conf"
bison_log_dir: "{{ bison_dir }}/log"
bison_tmp_dir: "{{ bison_dir }}/tmp"
bison_app_base_dir: "{{ bison_dir }}/app"
bison_source_base_dir: "{{ bison_dir }}/source"
bison_app_dir: "{{ bison_app_base_dir }}/bison-{{ bison_version }}"
bison_bin_dir: "{{ bison_app_dir }}/bin"
bison_lib_dir: "{{ bison_app_dir }}/lib"
bison_include_dir: "{{ bison_app_dir }}/include"
bison_share_dir: "{{ bison_app_dir }}/share"
bison_pkgconfig_dir: "{{ bison_lib_dir }}/pkgconfig"
bison_source_dir: "{{ bison_source_base_dir }}/bison-{{ bison_version }}"
