---
# defaults file for libgcrypt
# https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.11.tar.bz2
libgcrypt_install_user: "{{ ansible_user }}"
libgcrypt_install_group: "{{ ansible_user }}"
libgcrypt_version: "1.8.11"
# binary/source
libgcrypt_deploy_mode: "source"
libgcrypt_base_url: "{{ base_url }}"
libgcrypt_base_url_remote: "https://gnupg.org/ftp/gcrypt/libgcrypt"

libgcrypt_package_suffix: ".tar.gz"
libgcrypt_package_name_binary: "libgcrypt-{{ libgcrypt_version }}-{{ ansible_architecture }}{{ libgcrypt_package_suffix }}"
libgcrypt_package_name_source: "libgcrypt-{{ libgcrypt_version }}{{ libgcrypt_package_suffix }}"

libgcrypt_dir: "{{ base_dir }}/libgcrypt"
libgcrypt_app_dir: "{{ base_dir }}/libgcrypt/app"
libgcrypt_base_dir: "{{ libgcrypt_app_dir }}/libgcrypt-{{ libgcrypt_version }}"
libgcrypt_source_dir: "{{ libgcrypt_app_dir }}/source/libgcrypt-{{ libgcrypt_version }}"
