---
# tasks file for attr
# delete attr_source_dir attr_app_dir

- name: "delete {{ attr_source_dir }} {{ attr_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ attr_source_dir }}"
      - "{{ attr_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ attr_install_user }}"
      group: "{{ attr_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ attr_dir }} {{ attr_app_base_dir }} {{ attr_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ attr_install_user }}"
      group: "{{ attr_install_group }}"
      mode: 0755
  with_items:
      - "{{ attr_dir }}"
      - "{{ attr_app_base_dir }}"
      - "{{ attr_app_dir }}"
  when:
      - attr_deploy_method == "binary" or attr_deploy_method == "source"

# source dir
- name: "mkdir {{ attr_dir }} {{ attr_source_base_dir }}  {{ attr_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ attr_install_user }}"
      group: "{{ attr_install_group }}"
      mode: 0755
  with_items:
      - "{{ attr_source_base_dir }}"
      - "{{ attr_source_dir }}"
  when:
      - attr_deploy_method == "source"

# service dir
- name: "mkdir {{ attr_data_dir }} {{ attr_conf_dir }} {{ attr_log_dir }} {{ attr_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ attr_install_user }}"
      group: "{{ attr_install_group }}"
      mode: 0755
  with_items:
      - "{{ attr_data_dir }}"
      - "{{ attr_conf_dir }}"
      - "{{ attr_log_dir }}"
      - "{{ attr_tmp_dir }}"
  when:
      - attr_port is defined
