---
# tasks file for zlib
- name: "remove {{ zlib_source_dir }} {{ zlib_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ zlib_source_dir }}"
          - "{{ zlib_base_dir }}"

- name: "mkdir for zlib"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ zlib_install_user }}"
          group: "{{ zlib_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ zlib_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ zlib_app_dir }}"
          - "{{ zlib_base_dir }}"

- name: "mkdir {{ zlib_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ zlib_install_user }}"
          group: "{{ zlib_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ zlib_source_dir }}"
  when: zlib_deploy_mode == "source"
