---
# tasks file for zlib
# delete zlib_source_dir zlib_app_dir

- name: "delete {{ zlib_source_dir }} {{ zlib_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ zlib_source_dir }}"
      - "{{ zlib_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ zlib_install_user }}"
      group: "{{ zlib_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ zlib_dir }} {{ zlib_app_base_dir }} {{ zlib_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ zlib_install_user }}"
      group: "{{ zlib_install_group }}"
      mode: 0755
  with_items:
      - "{{ zlib_dir }}"
      - "{{ zlib_app_base_dir }}"
      - "{{ zlib_app_dir }}"
  when:
      - zlib_deploy_method == "binary" or zlib_deploy_method == "source"

# source dir
- name: "mkdir {{ zlib_dir }} {{ zlib_source_base_dir }}  {{ zlib_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ zlib_install_user }}"
      group: "{{ zlib_install_group }}"
      mode: 0755
  with_items:
      - "{{ zlib_source_base_dir }}"
      - "{{ zlib_source_dir }}"
      - "{{ zlib_build_dir }}"
  when:
      - zlib_deploy_method == "source"

# service dir
- name: "mkdir {{ zlib_data_dir }} {{ zlib_conf_dir }} {{ zlib_log_dir }} {{ zlib_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ zlib_install_user }}"
      group: "{{ zlib_install_group }}"
      mode: 0755
  with_items:
      - "{{ zlib_data_dir }}"
      - "{{ zlib_conf_dir }}"
      - "{{ zlib_log_dir }}"
      - "{{ zlib_tmp_dir }}"
  when:
      - zlib_port is defined
