---
# tasks file for isl
# delete isl_source_dir isl_app_dir

- name: "delete {{ isl_source_dir }} {{ isl_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ isl_source_dir }}"
      - "{{ isl_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ isl_install_user }}"
      group: "{{ isl_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ isl_dir }} {{ isl_app_base_dir }} {{ isl_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ isl_install_user }}"
      group: "{{ isl_install_group }}"
      mode: 0755
  with_items:
      - "{{ isl_dir }}"
      - "{{ isl_app_base_dir }}"
      - "{{ isl_app_dir }}"
  when:
      - isl_deploy_method == "binary" or isl_deploy_method == "source"

# source dir
- name: "mkdir {{ isl_dir }} {{ isl_source_base_dir }}  {{ isl_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ isl_install_user }}"
      group: "{{ isl_install_group }}"
      mode: 0755
  with_items:
      - "{{ isl_source_base_dir }}"
      - "{{ isl_source_dir }}"
  when:
      - isl_deploy_method == "source"

# service dir
- name: "mkdir {{ isl_data_dir }} {{ isl_conf_dir }} {{ isl_log_dir }} {{ isl_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ isl_install_user }}"
      group: "{{ isl_install_group }}"
      mode: 0755
  with_items:
      - "{{ isl_data_dir }}"
      - "{{ isl_conf_dir }}"
      - "{{ isl_log_dir }}"
      - "{{ isl_tmp_dir }}"
  when:
      - isl_port is defined
