---
# tasks file for isl
- name: "remove {{ isl_source_dir }} {{ isl_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ isl_source_dir }}"
          - "{{ isl_base_dir }}"

- name: "mkdir for isl"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ isl_install_user }}"
          group: "{{ isl_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ isl_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ isl_app_dir }}"
          - "{{ isl_base_dir }}"

- name: "mkdir {{ isl_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ isl_install_user }}"
          group: "{{ isl_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ isl_source_dir }}"
  when: isl_deploy_method == "source"
