---
# tasks file for isl by source
- name: "chown -R {{  isl_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ isl_install_user }}.{{ isl_install_group }} {{  isl_dir  }}"

# source
- name: "isl_deploy_method == 'source'"
  block:
      - name: "cd {{ isl_source_dir }};./configure --prefix={{ isl_app_dir }}"
        shell:
            chdir: "{{ isl_source_dir }}"
            cmd: "./configure --prefix={{ isl_app_dir }}"
      - name: "cd {{ isl_source_dir }};make -j{{ ansible_processor_vcpus }}"
        shell:
            chdir: "{{ isl_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ isl_source_dir }};make install"
        shell:
            chdir: "{{ isl_source_dir }}"
            cmd: make install
  when: isl_deploy_method == "source"

# isl_port standalone
- name: isl_port is defined
  block:
      - name: "cd {{ isl_source_dir }};./configure --prefix={{ isl_base_dir }}"
        become: true
        shell:
            chdir: "{{ isl_source_dir }}"
            cmd: "./configure --prefix={{ isl_base_dir }} --with-gmp-prefix={{ base_dir }}/gmp/app/gmp-{{ gmp_version }}"
      - name: "cd {{ isl_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ isl_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ isl_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ isl_source_dir }}"
            cmd: make install
  when:
      - isl_port is defined
      - isl_deploy_mode == "standalone"

# chown
- name: "chown -R {{  isl_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ isl_install_user }}.{{ isl_install_group }} {{  isl_dir  }}"
