---
# tasks file for pkgconfig
# delete pkgconfig_source_dir pkgconfig_app_dir

- name: "delete {{ pkgconfig_source_dir }} {{ pkgconfig_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ pkgconfig_source_dir }}"
      - "{{ pkgconfig_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ pkgconfig_install_user }}"
      group: "{{ pkgconfig_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ pkgconfig_dir }} {{ pkgconfig_app_base_dir }} {{ pkgconfig_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ pkgconfig_install_user }}"
      group: "{{ pkgconfig_install_group }}"
      mode: 0755
  with_items:
      - "{{ pkgconfig_dir }}"
      - "{{ pkgconfig_app_base_dir }}"
      - "{{ pkgconfig_app_dir }}"
  when:
      - pkgconfig_deploy_method == "binary" or pkgconfig_deploy_method == "source"

# source dir
- name: "mkdir {{ pkgconfig_dir }} {{ pkgconfig_source_base_dir }}  {{ pkgconfig_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ pkgconfig_install_user }}"
      group: "{{ pkgconfig_install_group }}"
      mode: 0755
  with_items:
      - "{{ pkgconfig_source_base_dir }}"
      - "{{ pkgconfig_source_dir }}"
  when:
      - pkgconfig_deploy_method == "source"

# service dir
- name: "mkdir {{ pkgconfig_data_dir }} {{ pkgconfig_conf_dir }} {{ pkgconfig_log_dir }} {{ pkgconfig_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ pkgconfig_install_user }}"
      group: "{{ pkgconfig_install_group }}"
      mode: 0755
  with_items:
      - "{{ pkgconfig_data_dir }}"
      - "{{ pkgconfig_conf_dir }}"
      - "{{ pkgconfig_log_dir }}"
      - "{{ pkgconfig_tmp_dir }}"
  when:
      - pkgconfig_port is defined
