---
# tasks file for libtool
- name: "remove {{ libtool_source_dir }} {{ libtool_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ libtool_source_dir }}"
          - "{{ libtool_base_dir }}"

- name: "mkdir for libtool"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ libtool_install_user }}"
          group: "{{ libtool_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ libtool_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ libtool_app_dir }}"
          - "{{ libtool_base_dir }}"

- name: "mkdir {{ libtool_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ libtool_install_user }}"
          group: "{{ libtool_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ libtool_source_dir }}"
  when: libtool_deploy_mode == "source"
