---
# tasks file for libtool
# delete libtool_source_dir libtool_app_dir

- name: "delete {{ libtool_source_dir }} {{ libtool_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ libtool_source_dir }}"
      - "{{ libtool_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtool_install_user }}"
      group: "{{ libtool_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ libtool_dir }} {{ libtool_app_base_dir }} {{ libtool_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtool_install_user }}"
      group: "{{ libtool_install_group }}"
      mode: 0755
  with_items:
      - "{{ libtool_dir }}"
      - "{{ libtool_app_base_dir }}"
      - "{{ libtool_app_dir }}"
  when:
      - libtool_deploy_method == "binary" or libtool_deploy_method == "source"

# source dir
- name: "mkdir {{ libtool_dir }} {{ libtool_source_base_dir }}  {{ libtool_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtool_install_user }}"
      group: "{{ libtool_install_group }}"
      mode: 0755
  with_items:
      - "{{ libtool_source_base_dir }}"
      - "{{ libtool_source_dir }}"
  when:
      - libtool_deploy_method == "source"

# service dir
- name: "mkdir {{ libtool_data_dir }} {{ libtool_conf_dir }} {{ libtool_log_dir }} {{ libtool_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ libtool_install_user }}"
      group: "{{ libtool_install_group }}"
      mode: 0755
  with_items:
      - "{{ libtool_data_dir }}"
      - "{{ libtool_conf_dir }}"
      - "{{ libtool_log_dir }}"
      - "{{ libtool_tmp_dir }}"
  when:
      - libtool_port is defined
