---
# tasks file for mpc
- name: "remove {{ mpc_source_dir }} {{ mpc_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ mpc_source_dir }}"
          - "{{ mpc_base_dir }}"

- name: "mkdir for mpc"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ mpc_install_user }}"
          group: "{{ mpc_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ mpc_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ mpc_app_dir }}"
          - "{{ mpc_base_dir }}"

- name: "mkdir {{ mpc_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ mpc_install_user }}"
          group: "{{ mpc_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ mpc_source_dir }}"
  when: mpc_deploy_method == "source"
