---
# tasks file for mpc
# delete mpc_source_dir mpc_app_dir

- name: "delete {{ mpc_source_dir }} {{ mpc_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ mpc_source_dir }}"
      - "{{ mpc_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ mpc_install_user }}"
      group: "{{ mpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ mpc_dir }} {{ mpc_app_base_dir }} {{ mpc_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ mpc_install_user }}"
      group: "{{ mpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ mpc_dir }}"
      - "{{ mpc_app_base_dir }}"
      - "{{ mpc_app_dir }}"
  when:
      - mpc_deploy_method == "binary" or mpc_deploy_method == "source"

# source dir
- name: "mkdir {{ mpc_dir }} {{ mpc_source_base_dir }}  {{ mpc_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ mpc_install_user }}"
      group: "{{ mpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ mpc_source_base_dir }}"
      - "{{ mpc_source_dir }}"
  when:
      - mpc_deploy_method == "source"

# service dir
- name: "mkdir {{ mpc_data_dir }} {{ mpc_conf_dir }} {{ mpc_log_dir }} {{ mpc_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ mpc_install_user }}"
      group: "{{ mpc_install_group }}"
      mode: 0755
  with_items:
      - "{{ mpc_data_dir }}"
      - "{{ mpc_conf_dir }}"
      - "{{ mpc_log_dir }}"
      - "{{ mpc_tmp_dir }}"
  when:
      - mpc_port is defined
