---
# tasks file for openssl
# delete openssl_source_dir openssl_app_dir

- name: "delete {{ openssl_source_dir }} {{ openssl_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ openssl_source_dir }}"
      - "{{ openssl_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ openssl_install_user }}"
      group: "{{ openssl_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ openssl_dir }} {{ openssl_app_base_dir }} {{ openssl_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ openssl_install_user }}"
      group: "{{ openssl_install_group }}"
      mode: 0755
  with_items:
      - "{{ openssl_dir }}"
      - "{{ openssl_app_base_dir }}"
      - "{{ openssl_app_dir }}"
  when:
      - openssl_deploy_method == "binary" or openssl_deploy_method == "source"

# source dir
- name: "mkdir {{ openssl_dir }} {{ openssl_source_base_dir }}  {{ openssl_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ openssl_install_user }}"
      group: "{{ openssl_install_group }}"
      mode: 0755
  with_items:
      - "{{ openssl_source_base_dir }}"
      - "{{ openssl_source_dir }}"
  when:
      - openssl_deploy_method == "source"

# service dir
- name: "mkdir {{ openssl_data_dir }} {{ openssl_conf_dir }} {{ openssl_log_dir }} {{ openssl_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ openssl_install_user }}"
      group: "{{ openssl_install_group }}"
      mode: 0755
  with_items:
      - "{{ openssl_data_dir }}"
      - "{{ openssl_conf_dir }}"
      - "{{ openssl_log_dir }}"
      - "{{ openssl_tmp_dir }}"
  when:
      - openssl_port is defined
