---
# tasks file for openssl
- name: "remove {{ openssl_source_dir }} {{ openssl_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ openssl_source_dir }}"
          - "{{ openssl_base_dir }}"

- name: "mkdir for openssl"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ openssl_install_user }}"
          group: "{{ openssl_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ openssl_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ openssl_app_dir }}"
          - "{{ openssl_base_dir }}"

- name: "mkdir {{ openssl_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ openssl_install_user }}"
          group: "{{ openssl_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ openssl_source_dir }}"
  when: openssl_deploy_mode == "source"
