---
# tasks file for mpfr
- name: "remove {{ mpfr_source_dir }} {{ mpfr_base_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: absent
  with_items:
          - "{{ mpfr_source_dir }}"
          - "{{ mpfr_base_dir }}"

- name: "mkdir for mpfr"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          owner: "{{ mpfr_install_user }}"
          group: "{{ mpfr_install_group }}"
          mode: 0755
  with_items:
          - "{{ base_dir }}"
          - "{{ mpfr_dir }}"
          - "{{ install_tmpdir }}"
          - "{{ mpfr_app_dir }}"
          - "{{ mpfr_base_dir }}"

- name: "mkdir {{ mpfr_source_dir }}"
  become: true
  file:
          path: "{{ item }}"
          state: directory
          mode: 0755
          owner: "{{ mpfr_install_user }}"
          group: "{{ mpfr_install_group }}"
  with_items:
          - "{{ base_dir }}"
          - "{{ mpfr_source_dir }}"
  when: mpfr_deploy_mode == "source"
