---
# defaults file for autoconf
# https://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz


# user
autoconf_install_user: "{{ ansible_user }}"
autoconf_install_group: "{{ ansible_user }}"
autoconf_version: "2.69"
# autoconf_port: "8032"

# standalone/cluster/pseudo_cluster
autoconf_deploy_mode: "standalone"

# binary/source/rpm/yum/dnf
autoconf_deploy_method: "source"

# url
autoconf_base_url: "{{ base_url }}"
autoconf_base_url_remote: "https://ftp.gnu.org/gnu/autoconf"

# package
autoconf_package_suffix: ".tar.gz"
autoconf_package_name_rpm: "autoconf-{{ autoconf_version }}.rpm"
autoconf_package_name_binary: "autoconf-{{ autoconf_version }}-{{ ansible_architecture }}{{ autoconf_package_suffix }}"
autoconf_package_name_source: "autoconf-{{ autoconf_version }}{{ autoconf_package_suffix }}"
autoconf_package_name: "{% if autoconf_deploy_method == 'rpm' %}{{ autoconf_package_name_rpm }}{% elif autoconf_deploy_method == 'binary' %}{{ autoconf_package_name_binary }}{% elif autoconf_deploy_method == 'source' %}{{ autoconf_package_name_source }}{% else %}{{ autoconf_package_name_source }}{% endif %}"

# 一台机器上部署相同服务时，通过不同端口号和不同的base_dir来区分是最佳的，这样不用修改目录结构
# 1. 通过变更base_dir和端口
# /data
# /data/autoconf
# /data/autoconf/data
# /data/autoconf/conf
# /data/autoconf/log
# /data/autoconf/tmp
# /data/autoconf/source
# /data/autoconf/app
# /data/autoconf/app/autoconf-{{ autoconf_version }}
# /data/autoconf/app/autoconf-{{ autoconf_version }}/bin
# /data/autoconf/app/autoconf-{{ autoconf_version }}/lib
# /data/autoconf/app/autoconf-{{ autoconf_version }}/lib/pkgconfig
# /data/autoconf/app/autoconf-{{ autoconf_version }}/include
# /data/autoconf/app/autoconf-{{ autoconf_version }}/share
# /data/autoconf/source/autoconf-{{ autoconf_version }}
autoconf_dir: "{{ base_dir }}/autoconf"
autoconf_data_dir: "{{ autoconf_dir }}/data"
autoconf_conf_dir: "{{ autoconf_dir }}/conf"
autoconf_log_dir: "{{ autoconf_dir }}/log"
autoconf_tmp_dir: "{{ autoconf_dir }}/tmp"
autoconf_app_base_dir: "{{ autoconf_dir }}/app"
autoconf_source_base_dir: "{{ autoconf_dir }}/source"
autoconf_app_dir: "{{ autoconf_app_base_dir }}/autoconf-{{ autoconf_version }}"
autoconf_bin_dir: "{{ autoconf_app_dir }}/bin"
autoconf_lib_dir: "{{ autoconf_app_dir }}/lib"
autoconf_include_dir: "{{ autoconf_app_dir }}/include"
autoconf_share_dir: "{{ autoconf_app_dir }}/share"
autoconf_pkgconfig_dir: "{{ autoconf_lib_dir }}/pkgconfig"
autoconf_source_dir: "{{ autoconf_source_base_dir }}/autoconf-{{ autoconf_version }}"
