---
# tasks file for findutils
# delete findutils_source_dir findutils_app_dir

- name: "delete {{ findutils_source_dir }} {{ findutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ findutils_source_dir }}"
      - "{{ findutils_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ findutils_install_user }}"
      group: "{{ findutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ findutils_dir }} {{ findutils_app_base_dir }} {{ findutils_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ findutils_install_user }}"
      group: "{{ findutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ findutils_dir }}"
      - "{{ findutils_app_base_dir }}"
      - "{{ findutils_app_dir }}"
  when:
      - findutils_deploy_method == "binary" or findutils_deploy_method == "source"

# source dir
- name: "mkdir {{ findutils_dir }} {{ findutils_source_base_dir }}  {{ findutils_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ findutils_install_user }}"
      group: "{{ findutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ findutils_source_base_dir }}"
      - "{{ findutils_source_dir }}"
  when:
      - findutils_deploy_method == "source"

# service dir
- name: "mkdir {{ findutils_data_dir }} {{ findutils_conf_dir }} {{ findutils_log_dir }} {{ findutils_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ findutils_install_user }}"
      group: "{{ findutils_install_group }}"
      mode: 0755
  with_items:
      - "{{ findutils_data_dir }}"
      - "{{ findutils_conf_dir }}"
      - "{{ findutils_log_dir }}"
      - "{{ findutils_tmp_dir }}"
  when:
      - findutils_port is defined
