---
# tasks file for findutils by source

# source
- name: "findutils_deploy_method == 'source'"
  block:
      - name: "cd {{ findutils_source_dir }};./configure --prefix={{ findutils_app_dir }}"
        become: true
        shell:
            chdir: "{{ findutils_source_dir }}"
            cmd: "./configure --prefix={{ findutils_app_dir }}"
      - name: "cd {{ findutils_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ findutils_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ findutils_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ findutils_source_dir }}"
            cmd: make install
  when: findutils_deploy_method == "source"

# findutils_port standalone
- name: findutils_port is defined
  block:
      - name: "cd {{ findutils_source_dir }};./configure --prefix={{ findutils_base_dir }}"
        become: true
        shell:
            chdir: "{{ findutils_source_dir }}"
            cmd: "./configure --prefix={{ findutils_base_dir }}"
      - name: "cd {{ findutils_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ findutils_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ findutils_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ findutils_source_dir }}"
            cmd: make install
  when:
      - findutils_port is defined
      - findutils_deploy_mode == "standalone"

# chown
- name: "chown -R {{  findutils_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ findutils_install_user }}.{{ findutils_install_group }} {{  findutils_dir  }}"
