---
# defaults file for work_mysql
# /data/tmpdir/mysql-8.0.26-aarch64.tar.gz
# /data/tmpdir/mysql-8.0.26-x86_64.tar.gz
# DONE
mysql_admin_init_password: "Root@1234"
mysql_version: "8.0.26"
mysql_port: "16315"

mysql_admin_init_user: "admin"
mysql_root_init_password: "{{ mysql_admin_init_password }}"
mysql_root_loacl_init_password: "{{ mysql_admin_init_password }}"
mysql_rep_init_user: "dbscale_internal"
mysql_rep_init_password: "{{ mysql_admin_init_password }}"
mysql_install_user: "{{ ansible_user }}"
mysql_install_group: "{{ ansible_user }}"
# binary/source
mysql_deploy_mode: "binary"
mysql_base_url: "{{ base_url }}"
mysql_base_url_remote: ""
mysql_package_suffix: ".tar.gz"
mysql_package_name_binary: "mysql-{{ mysql_version }}-{{ ansible_architecture }}{{ mysql_package_suffix }}"
mysql_package_name_source: "mysql-{{ mysql_version }}{{ mysql_package_suffix }}"
install_tmpdir: "{{ base_dir }}/tmpdir"
mysql_app_dir: "{{ base_dir }}/app"
mysql_app_base_dir: "{{ mysql_app_dir }}/mysql-{{mysql_version}}"
mysql_bin_dir: "{{ mysql_app_base_dir }}/bin"
# binary
mysql_mysqldata_dir: "{{ base_dir }}/mysqldata"
mysql_base_dir: "{{ mysql_mysqldata_dir }}/{{ mysql_uuid.stdout }}"
mysql_conf_dir: "{{ mysql_base_dir }}"
mysql_data_dir: "{{ mysql_base_dir }}/dbdata"
mysql_log_dir: "{{ mysql_base_dir }}/logfile"
mysql_tmp_dir: "{{ mysql_base_dir }}/tmp"
mysql_pid_dir: "{{ mysql_base_dir }}/pid"
mysql_socket_dir: "{{ mysql_base_dir }}/socket"
# source
mysql_source_dir: "{{ mysql_app_dir }}/source/mysql-{{ mysql_version }}"
# 一般来说，设置为总 RAM 的 50% – 70% 作为起点
innodb_buffer_pool_size: "{{ ansible_memtotal_mb * 1 // 2 |int }}"








