---
# tasks file for grub
# delete grub_source_dir grub_app_dir

- name: "delete {{ grub_source_dir }} {{ grub_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ grub_source_dir }}"
      - "{{ grub_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grub_install_user }}"
      group: "{{ grub_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ grub_dir }} {{ grub_app_base_dir }} {{ grub_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grub_install_user }}"
      group: "{{ grub_install_group }}"
      mode: 0755
  with_items:
      - "{{ grub_dir }}"
      - "{{ grub_app_base_dir }}"
      - "{{ grub_app_dir }}"
  when:
      - grub_deploy_method == "binary" or grub_deploy_method == "source"

# source dir
- name: "mkdir {{ grub_dir }} {{ grub_source_base_dir }}  {{ grub_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grub_install_user }}"
      group: "{{ grub_install_group }}"
      mode: 0755
  with_items:
      - "{{ grub_source_base_dir }}"
      - "{{ grub_source_dir }}"
  when:
      - grub_deploy_method == "source"

# service dir
- name: "mkdir {{ grub_data_dir }} {{ grub_conf_dir }} {{ grub_log_dir }} {{ grub_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ grub_install_user }}"
      group: "{{ grub_install_group }}"
      mode: 0755
  with_items:
      - "{{ grub_data_dir }}"
      - "{{ grub_conf_dir }}"
      - "{{ grub_log_dir }}"
      - "{{ grub_tmp_dir }}"
  when:
      - grub_port is defined
