---
# tasks file for autoconf
# delete autoconf_source_dir autoconf_app_dir

- name: "delete {{ autoconf_source_dir }} {{ autoconf_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ autoconf_source_dir }}"
      - "{{ autoconf_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ autoconf_install_user }}"
      group: "{{ autoconf_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ autoconf_dir }} {{ autoconf_app_base_dir }} {{ autoconf_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ autoconf_install_user }}"
      group: "{{ autoconf_install_group }}"
      mode: 0755
  with_items:
      - "{{ autoconf_dir }}"
      - "{{ autoconf_app_base_dir }}"
      - "{{ autoconf_app_dir }}"
  when:
      - autoconf_deploy_method == "binary" or autoconf_deploy_method == "source"

# source dir
- name: "mkdir {{ autoconf_dir }} {{ autoconf_source_base_dir }}  {{ autoconf_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ autoconf_install_user }}"
      group: "{{ autoconf_install_group }}"
      mode: 0755
  with_items:
      - "{{ autoconf_source_base_dir }}"
      - "{{ autoconf_source_dir }}"
  when:
      - autoconf_deploy_method == "source"

# service dir
- name: "mkdir {{ autoconf_data_dir }} {{ autoconf_conf_dir }} {{ autoconf_log_dir }} {{ autoconf_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ autoconf_install_user }}"
      group: "{{ autoconf_install_group }}"
      mode: 0755
  with_items:
      - "{{ autoconf_data_dir }}"
      - "{{ autoconf_conf_dir }}"
      - "{{ autoconf_log_dir }}"
      - "{{ autoconf_tmp_dir }}"
  when:
      - autoconf_port is defined
