---
# tasks file for libgpg_error by source

# source
- name: "libgpg_error_deploy_method == 'source'"
  block:
      - name: "cd {{ libgpg_error_source_dir }};./configure --prefix={{ libgpg_error_app_dir }}"
        become: true
        shell:
            chdir: "{{ libgpg_error_source_dir }}"
            cmd: "./configure --prefix={{ libgpg_error_app_dir }}"
      - name: "cd {{ libgpg_error_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ libgpg_error_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ libgpg_error_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ libgpg_error_source_dir }}"
            cmd: make install
  when: libgpg_error_deploy_method == "source"

# libgpg_error_port standalone
- name: libgpg_error_port is defined
  block:
      - name: "cd {{ libgpg_error_source_dir }};./configure --prefix={{ libgpg_error_base_dir }}"
        become: true
        shell:
            chdir: "{{ libgpg_error_source_dir }}"
            cmd: "./configure --prefix={{ libgpg_error_base_dir }}"
      - name: "cd {{ libgpg_error_source_dir }};make -j{{ ansible_processor_vcpus }}"
        become: true
        shell:
            chdir: "{{ libgpg_error_source_dir }}"
            cmd: "make -j{{ ansible_processor_vcpus }}"
      - name: "cd {{ libgpg_error_source_dir }};make install"
        become: true
        shell:
            chdir: "{{ libgpg_error_source_dir }}"
            cmd: make install
  when:
      - libgpg_error_port is defined
      - libgpg_error_deploy_mode == "standalone"

# chown
- name: "chown -R {{  libgpg_error_dir  }}"
  become: true
  shell:
      cmd: "chown -R {{ libgpg_error_install_user }}.{{ libgpg_error_install_group }} {{  libgpg_error_dir  }}"
