---
# tasks file for gawk
# delete gawk_source_dir gawk_app_dir

- name: "delete {{ gawk_source_dir }} {{ gawk_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ gawk_source_dir }}"
      - "{{ gawk_app_dir }}"

# basic dir
- name: "mkdir {{ base_dir }} {{ install_tmpdir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gawk_install_user }}"
      group: "{{ gawk_install_group }}"
      mode: 0755
  with_items:
      - "{{ base_dir }}"
      - "{{ install_tmpdir }}"

# binary and source dir
- name: "mkdir {{ gawk_dir }} {{ gawk_app_base_dir }} {{ gawk_app_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gawk_install_user }}"
      group: "{{ gawk_install_group }}"
      mode: 0755
  with_items:
      - "{{ gawk_dir }}"
      - "{{ gawk_app_base_dir }}"
      - "{{ gawk_app_dir }}"
  when:
      - gawk_deploy_method == "binary" or gawk_deploy_method == "source"

# source dir
- name: "mkdir {{ gawk_dir }} {{ gawk_source_base_dir }}  {{ gawk_source_dir }} "
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gawk_install_user }}"
      group: "{{ gawk_install_group }}"
      mode: 0755
  with_items:
      - "{{ gawk_source_base_dir }}"
      - "{{ gawk_source_dir }}"
  when:
      - gawk_deploy_method == "source"

# service dir
- name: "mkdir {{ gawk_data_dir }} {{ gawk_conf_dir }} {{ gawk_log_dir }} {{ gawk_tmp_dir }}"
  become: true
  file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gawk_install_user }}"
      group: "{{ gawk_install_group }}"
      mode: 0755
  with_items:
      - "{{ gawk_data_dir }}"
      - "{{ gawk_conf_dir }}"
      - "{{ gawk_log_dir }}"
      - "{{ gawk_tmp_dir }}"
  when:
      - gawk_port is defined
